### ISSUE TITLE
Selecting the correct item for an icon

### ISSUE THREAD

**Issue by CodeDoctorDE** [erikzimmermann/WarpSystem-IssueTracker#121]
Da das Nehmen vor dem Öffnen etwas schwer ist, habe ich eine Idee:

Beim Ändern des Symbols schließt sich das GUI und man muss das Item droppen. Zum Abbrechen einfach bewegen.

**Comment by erikzimmermann** [comment]
Dann kann man aber auch nur das Item auswählen, was in der Hotbar ist. Wenn man dennoch das eigene Inventar öffnen möchte, um das Item droppen zu können, wäre das zu aufwendig.

**Comment by erikzimmermann** [comment]
New inventory (9x1) filled with glass, except for the middle slot, to free up space for the selected item.

**Comment by erikzimmermann** [comment]
Not necessary
