### ISSUE TITLE
EssentialsX duplicate command /setwarp

### ISSUE THREAD

**Issue by maever** [erikzimmermann/WarpSystem-IssueTracker#131]
To my understanding WarpSystem's warp commands replace EssentialX's warp commands https://essinfo.xeya.me/index.php?page=commands , as seen here, you both utilize same commands . The one downside this has is that I use a dynmap addon that used to show warp locations on the map, which I can now no longer alter. 

Is there any chance you could add an option which would allow me to either utilize both warp systems of essentialsX as well as your own? (by maybe changing your command to /setwarp2 when a compatibility configuration is enabled ? )  Or better maybe assist to create a dynmap plugin that shows your warps on dynmap .

**Comment by erikzimmermann** [comment]
Sorry for the late response.

You could use the plugin name as prefix in your command. Something like "/essentials:setwarp". I won't change the command to /setwarp2, sorry.
