### ISSUE TITLE
Costs don't go through

### ISSUE THREAD

**Issue by razaphale** [erikzimmermann/WarpSystem-IssueTracker#132]
I have vault installed and an economy plugin but the costs for the warps doesn't go through even though I've set it at 300 coin/s. When I use the warp it says I've been charged 0.0 

Is this due to me being an admin?

**Comment by erikzimmermann** [comment]
Yes, with a special permission, the costs will set to 0.

Try to negate this permission and test it again: "WarpSystem.ByPass.Teleport.Costs"
