### ISSUE TITLE
Warpsystem doesn't work with TradeSystem plugin and Multiverse at the same time.

### ISSUE THREAD

**Issue by AnthonyLNguyen** [erikzimmermann/WarpSystem-IssueTracker#183]
Warpsystem_v4,1.50-free won't enable if  TradeSystem (1.1.1) and Multiverse-Core (Tested with 4.0.0 and 4.1.0) are enabled. Deleting either TradeSystem or Multiverse fixes it

**Comment by erikzimmermann** [comment]
My TradeSystem has an old api. They don’t work together at the moment.
Multiverse is supported and should work.

**Comment by erikzimmermann** [comment]
Fixed
