### ISSUE TITLE
Feature Request: User Teleport Pads with limits

### ISSUE THREAD

**Issue by TKwSni** [erikzimmermann/WarpSystem-IssueTracker#185]
Hi I was thinking if it was possible to add, per user public teleport pads (pressure plates), that they can build but they have limits on how many they can build.

like warps.userpads.<limit>

My idea:
They place a presureplate with a name using commands /pads create name they are asked to go to the destination and run the command /pads finish name on another pressure plate, and both plates are linked, now you can use the plate to go to eachother.

The limit is to avoid tons of pads on the world. It would be also a nice addition to only allow per world pads.

**Comment by erikzimmermann** [comment]
Hey, already thought about pressure plates as feature object, but I wanted to improve all existing features before adding new things.

I'll create a milestone for this ^^

**Comment by erikzimmermann** [comment]
Denied. Too specific for my WarpSystem. This could be a new plugin.
