### ISSUE TITLE
TempWarps: Rental time selector

### ISSUE THREAD

**Issue by dorsax** [erikzimmermann/WarpSystem-IssueTracker#192]
Currently it takes a lot of time to get the rental time for Tempwarps to its max, esp. if it’s up to 30 days.

Maybe it’s better to have a possibility to switch between minutes, hours, days to change. 
Like press ALT will switch through those three and you can add/remove that amount of time to/from your rental time with a mouse click

**Comment by erikzimmermann** [comment]
Same thing like in the key editor
