### ISSUE TITLE
Vielleicht eine Animationmode

### ISSUE THREAD

**Issue by CodeDoctorDE** [erikzimmermann/WarpSystem-IssueTracker#22]
Wenn man den Animationsmodus anschaltet wird man für X Sekunden in ein Raum teleportiert.

Ist mir gerade eingefallen, da ich gerne ein Öpnv System mache und wenn man in ein Bus teleportiert wird, wäre es vielleicht spannend!

**Comment by erikzimmermann** [comment]
Sowas ähnliches ist bereits in #17 geplant. Da werd ich dann ne zwischen Position optional machen. Dann kannste damit die Position im Bus setzen.

**Comment by CodeDoctorDE** [comment]
Okay, danke!
