### ISSUE TITLE
Random Teleport Requests

### ISSUE THREAD

**Issue by HunterJacobs** [erikzimmermann/WarpSystem-IssueTracker#229]
- Random Teleport user timer. (limit /rtp to a set amount of time)
- Random Teleport first join buffer (no limit/  or timer)

**Comment by erikzimmermann** [comment]
To open the feature for unlimited teleports within a certain amount of time?

**Comment by HunterJacobs** [comment]
Yea, kinda an old idea. What if there was a setting that gave users a default join amount of RTP requests? So let's say you get 10 to get started and after that, it costs whatever per rtp?

**Comment by erikzimmermann** [comment]
Already implemented.

`"warpsystem.randomteleporters.free.1" » This permissions means, that the player with that permission has a standard amount of 1 free random teleport`
