### ISSUE TITLE
Support for GemsEconomy

### ISSUE THREAD

**Issue by CodeDoctorDE** [erikzimmermann/WarpSystem-IssueTracker#23]
Es ist kompaktibel mit Vault, aber man kann nicht mehrere Währungen machen.

Wenn es geht, würde ich vielleicht eine Möglichkeit machen, dass man die WarpSigns mit Geldscheinen bezahlen kann (ist im Plugin integriert).

GemsEconomy: https://www.spigotmc.org/resources/gemseconomy.19655/

**Comment by erikzimmermann** [comment]
Du meinst, dass User WarpSigns mit Geld erstellen können sollen?

**Comment by CodeDoctorDE** [comment]
Nein, wenn man drauf drückt, dass man Geld bezahlt (auch Geldscheine wenn möglich)

Das man im ganzen Plugin mit mehreren Währungen bezahlt.

**Comment by erikzimmermann** [comment]
Ich werde mal schauen, was ich machen kann.

**Comment by erikzimmermann** [comment]
Um das hier mal wieder aufzugreifen. In #321 hab ich das von der anderen Seite betrachtet. Dann kann man auch endlich mehrere Währungen auswählen, allerdings nur als Admin und nicht als Spieler, da ich ansonsten von jedem die Prioritäten speichern müsste. Wäre das noch passend?

**Comment by CodeDoctorDE** [comment]
Alles klar :D
