### ISSUE TITLE
MC1.15.1 - WarpSystem 4.1.10 Config Reload Issue

### ISSUE THREAD

**Issue by cory1768** [erikzimmermann/WarpSystem-IssueTracker#235]
If I make any changes to the config file or if I don't make any changes to the config file generated by the plugin. Upon each server restart or reloading the plugin, it will always generate a new configuration file with the same error message:

[Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 2, column 11:
    WarpSystem:
              ^

**Comment by erikzimmermann** [comment]
Hey, is this issue still open?
