### ISSUE TITLE
Could not enable correctly on server start

### ISSUE THREAD

**Issue by Virenbar** [erikzimmermann/WarpSystem-IssueTracker#237]
After updating server from 1.14.4 to 1.15.1 plugin can't load.
**Server:** Paper-45 1.15.1
**WarpSystem:** [4.1.10-free]

[WarpSystemConfig.zip](https://github.com/CodingAir/WarpSystem-IssueTracker/files/4054715/WarpSystemConfig.zip)
[ErrorReport.txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/4054716/ErrorReport.txt)
[latest.log](https://github.com/CodingAir/WarpSystem-IssueTracker/files/4054727/latest.log)

**Comment by erikzimmermann** [comment]
Thank you!

**Comment by Virenbar** [comment]
Found the cause of the error. One of the warps was named using only numbers. In SimpleWarps.yml on line 27.

**Comment by erikzimmermann** [comment]
Support for names that contain only numbers
