### ISSUE TITLE
TempWarps with spaces in the name

### ISSUE THREAD

**Issue by nicostrebel** [erikzimmermann/WarpSystem-IssueTracker#241]
Users have the option to use spaces in the name of a temp warp. However, this temp warp can then no longer be deleted.

Temp-Warp Name: Somewhere far away

Command not working: /tempwarps delete Somewhere far away
Command also not working: /tempwarps delete "Somewhere far away"

**Comment by erikzimmermann** [comment]
Fixed for PlayerWarps
