### ISSUE TITLE
[Suggestion] More features for the back command

### ISSUE THREAD

**Issue by TKwSni** [erikzimmermann/WarpSystem-IssueTracker#242]
I would like to enable the back feature but, there are some missing features that essentials has.

- There are two /back levels by permissions:

1. /back to last tp,tpa,tpahere,tp by other plugins like towny /t spawn for example (there are some tps that should be ignored like setback from anticheat plugins)

2. /back to all tps from first level and death position

It would be nice to have this, as some server s might benefit from this, for examble in mine, I have a rankup system, and I allow them only to use /back on death after they reached certain level.

- Also, essentials /back works unlimited times, so you use it all the times you want to go to the last position, that includes the last position where you used /back command.

**Comment by erikzimmermann** [comment]
How does the setback from anticheat plugins work?

> Also, essentials /back works unlimited times, so you use it all the times you want to go to the last position, that includes the last position where you used /back command.

Yeah, it's very basic. That's the reason why I provide a history of different positions. I thought that this would be better.
But I can add this soon if you prefer the basic way.

**Comment by TKwSni** [comment]
history of different positions? so you can choose a different back? how to use that ? maybe you can implement both  as an option in the config

The setback from anticheats plugins, is just that it sets the player back if it thinks you went past the minecraft limits, I dont really know how they do it, but some plguins record that as a teleport and when you use /back it uses that position.

**Comment by erikzimmermann** [comment]
> history of different positions? so you can choose a different back? how to use that ? maybe you can implement both as an option in the config
> 
> The setback from anticheats plugins, is just that it sets the player back if it thinks you went past the minecraft limits, I dont really know how they do it, but some plguins record that as a teleport and when you use /back it uses that position.

Ah ok.

I’ll add both methods and a variable in the config to toggle this.

My plugin saves the (e.g.) 3 last back positions. If you use /back you’ll be teleported to the latest back position the plugin knows. Then, this position will be removed from that history. If you use /back now you’ll be teleported to the new latest back position (the first back position has been removed already).

**Comment by erikzimmermann** [comment]
@TKwSni 
Do you know a plugin, which ignore setbacks of anti cheat plugins?

As far as I know, I can't detect any kickbacks from anti-cheat plugins because the teleport events are triggered anonymously.

**Comment by erikzimmermann** [comment]
Level 1 (/back to last tps including tpa and these stuff): `WarpSystem.Use.TeleportCommand.Back`
Level 2 (/back to level 1 and death positions): `WarpSystem.Use.TeleportCommand.Back.Deaths`

If the history size is set to 1, /back will be recognized as teleport.
