### ISSUE TITLE
[Random TP] Rework

### ISSUE THREAD

**Issue by mellowism** [erikzimmermann/WarpSystem-IssueTracker#243]
I would like to have my lobby on a different server than my survival server. For that I want to be able to push a button with a command when clicking (using another plugin that does the command). Clicking the button should random teleport the player to a specific server and specific world on that server and to a random location. 

Can't find any other rtp plugin that has this feature.

**Comment by erikzimmermann** [comment]
Something like `/rtp go [player] {server-00, server-01, server-02; world-00, world-01}`?
The plugin chooses a random server out of the provided server list and a random world out of the provided world list.

But this would use the random teleport configuration of the target server and the spawn position of the player on that server as base position. The random offset is added to the base position to arrive at the random position.

**Comment by mellowism** [comment]
This would be really cool :)

**Comment by erikzimmermann** [comment]
Block blacklist
