### ISSUE TITLE
/tpa auto fill grabs displayname instead of playername

### ISSUE THREAD

**Issue by tiarnia** [erikzimmermann/WarpSystem-IssueTracker#248]

**Comment by erikzimmermann** [comment]
Which one should be used??

**Comment by tiarnia** [comment]
player name should

**Comment by erikzimmermann** [comment]
Yep... Got it. Thanks!

![image](https://user-images.githubusercontent.com/23747243/76908556-45ead100-68a9-11ea-8d85-e23bbeeaf1cf.png)
