### ISSUE TITLE
[Suggestion] Merge Effectportals and Nativeportals together

### ISSUE THREAD

**Issue by mellowism** [erikzimmermann/WarpSystem-IssueTracker#252]
I would like to have particle effects and also hologram in native portals. I could work around this by doing a effect portal but it's a but messy to get it in center and so on... Native portals are better when it comes to get it to look good inside of other blocks. 

Also the length of name is an issue when you try to use color codes etc. Tried to do a name as "CreativePlayground#1" with color codes between each letter. Wasn't possible unfortunately. Too many characters here: &6C&er&ce&2a&bt&di&fvePlayground#1

**Comment by erikzimmermann** [comment]
I'll try to merge the two portal types... but I think it's gonna be very difficult.

**Comment by mellowism** [comment]
How about just adding particle effect as portal block under appearance in Nativeportals? Just an example on how I've done it and the look I'm after: https://i.imgur.com/yWSJ6B2.png

**Comment by erikzimmermann** [comment]
Is it not simply an effect portal?

**Comment by mellowism** [comment]
They way you create them is very different. The Native Portal gui is very intuitive. The effect portal not as much imho. 

What I am after specifically, is just to add effects to native portals. When placing portal blocks, and then choose what kind of blocks they should be, (air, lava, nether, the end gate etc) it would be awesome if there could be an effect option. That way the effects would move in a more suitable pattern, inside the gate. 

The one in the image I managed to create by adjusting the size of the effect portal, but it is still moving in a circular pattern, and it doesn't look that good, and its not completely filled up, and it took a lot of time tinkering to get it in place the way it is now.

**Comment by erikzimmermann** [comment]
Maybe a new page for particles:

**Particle effects**
_Animation_Slot_0_ | _Animation_Slot_1_ | _Animation_Slot_2_ | _Animation_Slot_3_ | _Animation_Slot_4_

And every animation button has an option to center its animation.
By left clicking an animation button you'll go into the animations editor. The inventory GUI is closed and the hotbar GUI is opened.

What do you think about it?

I cannot completely move the animations editor into an inventory based GUI. Then you can no longer see your changes. But this connection between native portal and animation could merge both portal types together and provide some new options like centering the effect animations.

**Comment by mellowism** [comment]
If I understand correctly, animation slot being a slot to put an animation, making it possible to add many animations. Yes, absolutely :)

**Comment by erikzimmermann** [comment]
Yes. Just like the effect portal editor has its five animation slots.

**Comment by erikzimmermann** [comment]
### Todo
- [x] Particle effect page
  - Choose existing animations for animations list on page item (create new)
  - Up to 6 animation slots
    - Instructions = LEFT: Add/Edit; RIGHT: Remove (if animation available)
      - Editing (like old effect portals)
      - Merge animation height, radius, speed & type to one class: options
      - New button: position (Left: set position to player's position; Right: align to watched block (not only portal blocks))
![image](https://user-images.githubusercontent.com/23747243/78362085-c142c700-75b9-11ea-986f-be16cb727256.png)
- [x] Set portal blocks
  - ~Remove set-block button from option page~
  - ~Rename "portal material" page into "portal blocks"~
  - ~By clicking a portal material the inventory GUI is closed and the user can build some blocks with the chosen material~
  - Move set-block button to appearance page
  - By clicking this button the inventory is closed and the user get all diferent portal type blocks in his hotbar
- [x] Hologram
  - New button on options page
  - Leftclick: Edit (Opens different hotbar GUI for positioning, height, text, no-permissions-text)
- [x] Spawn position
  - Add button to set the spawn position of this portal to connect portals 
- [x] Destination page
  - new portal destiantion adapter (API)
