### ISSUE TITLE
/tp coords do not work properly

### ISSUE THREAD

**Issue by Stixil** [erikzimmermann/WarpSystem-IssueTracker#268]
For some reason, when using /tp as staff, the plugin now acts super strange and does not bring us to where we selected. Here is an example of trying /tp 0 80 0 and the result.
![tp bug](https://user-images.githubusercontent.com/53889383/78290356-a573ee00-74f1-11ea-8e86-fbbcc4daab51.PNG)

**Comment by erikzimmermann** [comment]
Thank you. I’ll take a look at it tomorrow. Please add me on discord (CodingAir#0281). There I can send you hotfixes right away.

**Comment by Stixil** [comment]
Request sent!
