### ISSUE TITLE
Manage First Join Spawns

### ISSUE THREAD

**Issue by HunterJacobs** [erikzimmermann/WarpSystem-IssueTracker#274]
Essentials doesn't seem to manage this well this plugin is installed. Can you add an option to manage first join spawns for tutorials?

**Comment by erikzimmermann** [comment]
Sure. I could send you some test jars if you add me on Discord (CodingAir#0281).

**Comment by erikzimmermann** [comment]
## Todo ##
* `/spawn` to teleport to spawn (optional)
* `/setspawn` sets the spawn position
* `/setspawn edit` to edit spawn attributes
  * spawn usage option: global/local/first spawn (last one disables the /spawn command)
  * message option
  * broadcast message option
  * fireworks option
  * Use for respawn: global/local/disabled
* Custom aliases
