### ISSUE TITLE
Not enough space in anvil gui for long command

### ISSUE THREAD

**Issue by mellowism** [erikzimmermann/WarpSystem-IssueTracker#275]
Related to what I mentioned here when trying to name a portal: #252 

I just tried to create a portal that executed a command. The command: 
/lp user promote %player% newplayertrack

The anvil gui only takes in 35 characters so this isn't possible. 

Also %player% placeholder isn't a thing apparently, is there a player placeholder?

Edit: Been playing around with commands now, something isn't right. I tried using different commands and some work, and some don't. Something with how it is executed. 
Example: 
/say hello - doesn't work
/gms - works.

**Comment by erikzimmermann** [comment]
Regarding anvil guis: The only chat input method I could implement is a chat button, which suggests a command to write some text.

**Comment by mellowism** [comment]
If I understand correctly you are prompted to type a normal chat to enter a name/command. 

I like plugins that do that. Best user experience is when you are prompted with a chat, and doesn't have to press "t" yourself to open chat.

**Comment by mellowism** [comment]
I want to add here as well that I like your use of anvil gui, and I'm sure others do as well. So if possible the best solution would be to increase the character cap in that anvil if possible... Otherwise I'm not sure it's worth it. You can always work around the cap. I created a alias for my command that shortened it for example...

**Comment by erikzimmermann** [comment]
I can’t increase the character cap and I can’t open the chat without clicking a button in the chat. Both options are client side.
What I can do is adding an option to add things in the chat and keeping the anvil GUI function (leftclick: anvil, shift-leftclick: chat)

**Comment by erikzimmermann** [comment]
I just searched a little bit and remembered the command block GUI. Maybe this allows more characters as anvil GUIs.

EDIT: CommandBlockGUIs only work up to MC 1.7... This option is out.
EDIT EDIT: The "Book and Quill" GUI maybe... (This would take a rightclick with that book in your hand [1.8-1.13]. In 1.14+ it can be done automaticly)

**Comment by mellowism** [comment]
Haven't seen Book and quill in action. It is an interesting idea!
