### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by spiker5032** [erikzimmermann/WarpSystem-IssueTracker#285]
**Portal costs** Be able to set costs of each portal with GUI block Right click to set cost (default) 0 for nothing 

Rtp to different worlds with portals

Blacklist blocks not to teleport on
(Water, Flowing water, Lava)

Possibly random teleport within a region?
/rtp (Region)

Ability to copy animations (so we can use the same animations and recolor)

Entity Portals? (Gems, heads)

**Comment by erikzimmermann** [comment]
~Portal costs Be able to set costs of each portal with GUI block Right click to set cost (default) 0 for nothing~ Done

~Rtp to different worlds with portals~ (Already in #243)

~Blacklist blocks not to teleport on
(Water, Flowing water, Lava)~ (Already in #243)

What do you mean with entity portals? Do you want portals, which teleport all entities?

**Comment by spiker5032** [comment]
More like Portals that you can have entities as the particle like what Block Particles has
https://i.gyazo.com/929b754e016413cb2967586058f6e16d.mp4

Also maybe Command Portals for Buyers?

Go through a portal and can execute commands that you set in the GUI Like this
https://i.gyazo.com/f848adcefa9fb01f344f5c1cdec24fce.mp4

**Comment by erikzimmermann** [comment]
> More like Portals that you can have entities as the particle like what Block Particles has
> https://i.gyazo.com/929b754e016413cb2967586058f6e16d.mp4
> 
> Also maybe Command Portals for Buyers?
> 
> Go through a portal and can execute commands that you set in the GUI Like this
> https://i.gyazo.com/f848adcefa9fb01f344f5c1cdec24fce.mp4

Commands can already be added to your portal. Just check out my latest release!

**Comment by erikzimmermann** [comment]
Regarding your entity animation... I think this is a too specific feature... 

Gonna close this issue now. Random tp suggestions are already in #243
