### ISSUE TITLE
Mislinking global warps

### ISSUE THREAD

**Issue by Sylensky** [erikzimmermann/WarpSystem-IssueTracker#298]
Hi,

i just wanted to know if someone else noticed that with the v4.1.10 some globalwarps get mislinked to another globalwarp.
As for example a player wants to warp from lobby to skyblock and the skyblock world contains other worlds where a globalwarp is linked to. It sometimes happen that the user get teleported to the other globalwarp on the skyblock server.
Is it still a thing or did it got fixed with the latest version? 
I wasn't able to update till now but i guess i will so soon.

**Comment by erikzimmermann** [comment]
This issue appeared last year once and might be already fixed. I’ll release a new update on Saturday.

**Comment by Sylensky** [comment]
Thanks for quick response. I might update during the weekend too not sure yet. Since i gotta buy premium now so that i dont have to change features for players.

**Comment by erikzimmermann** [comment]
Would be great if you could join my [Discord server](https://discord.gg/4eVAhKz) or add me on Discord (CodingAir# 0281) to discuss this issue.

**Comment by erikzimmermann** [comment]
Temporarily closed
