### ISSUE TITLE
[Back] BungeeWide /back

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-IssueTracker#305]
* User profiles for back data

**Comment by erikzimmermann** [comment]
~Waiting for #418 for first MySQL implementation.~

**Comment by benevolent2012** [comment]
Hello @CodingAir, I see that this has been removed from 4.2.8 milestone, but can you add this perhaps to an upcoming release?
It's kind of hard to use any of the 'bungee-wide' features without having a proper /back.

For example, when players use playerwarps that go from one server to another they won't be able to /back to the location they were in before they warped.

**Comment by erikzimmermann** [comment]
Todo: Move back-data into temporary cache (~ 10 minutes) to allow /back even after reconnecting
