### ISSUE TITLE
[PlayerWarp] PlayerWarps gone after reload

### ISSUE THREAD

**Issue by AWi92** [erikzimmermann/WarpSystem-IssueTracker#318]
**Describe the bug**
When I create a playerwarp, I can use it perfectly while I'm online. When I reconnect the server all playerwarps are gone. If I reload the config, all the warps are there again...
The Auto-Delete Config is on 14d. 

**To Reproduce**
1. Enter the Server
2. Create a PlayerWarp
3. Test the new Warp
4. Reconnect the Server
5. Try to teleport to the created PlayerWarp

**Expected behavior**
The PlayerWarps should be permernant.

**Additional context**
Server: Spigot 1.14.4
Plugin: 4.2.4

**Comment by erikzimmermann** [comment]
Thank you. Gonna check this today/tomorrow.

**Comment by erikzimmermann** [comment]
I tried it and it worked fine for me. Can you send me your PlayerWarpConfig.yml?

**Comment by AWi92** [comment]
Sure, I don't think that I edited anything in there. 

I'm also on your Discord with the same Username if this makes communication easier for you

[PlayerWarpConfig.zip](https://github.com/CodingAir/WarpSystem-IssueTracker/files/4638636/PlayerWarpConfig.zip)
