### ISSUE TITLE
[Interactive Blocks] New "linkable feature"

### ISSUE THREAD

**Issue by mibby** [erikzimmermann/WarpSystem-IssueTracker#319]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add an option to bind global and player warps to a button and/or pressure plate location?

**Describe the solution you'd like**
A command to bind warp locations to a button / pad.

**Additional context**
I'm migrating from the plugin ButtonWarp, which I used to have commands and warp locations tied to button interactions. 

https://dev.bukkit.org/projects/buttonwarp
https://www.spigotmc.org/resources/buttontp.22749/

Unfortunately the plugin is a bit outdated now and is causing sync chunk load lag, but no viable alternatives with the same feature-set exists.

**Comment by erikzimmermann** [comment]
Sounds like a complete new feature. Like interactive blocks. This would fit really nice to my #243. Then I could remove this feature there.

This feature would get all functions of my warp signs. Is that everything you need?

**Comment by mibby** [comment]
You'll have to excuse my ignorance, I haven't actually looked into what your warp signs feature includes yet. But I'd be happy to pay for the premium version of your warp plugin if you implement this as a new feature for it and manage to replicate what is possible/included with ButtonWarp / ButtonTP. 

I have looked around and found no viable alternative to accomplish what you can do with those legacy plugins and recently, it has been causing chunk sync lag when players interact to teleport. :( It hasn't had any active development since 2013 so it's not likely it will be updated to support the new async api in paper spigot.

**Comment by erikzimmermann** [comment]
This will be a good one. I could send you some pre releases if you like to test it first.

**Comment by mibby** [comment]
Sure, I'd be happy to help test.

**Comment by mibby** [comment]
Did you have any timeframe when you expect to implement this type of feature?

**Comment by erikzimmermann** [comment]
2-4 weeks maybe. But I can't estimate this perfectly.

**Comment by mibby** [comment]
Bumping feature request. :(

**Comment by erikzimmermann** [comment]
It will support the basic destination scheme and basic stuff like permission, commands, ...

**Comment by erikzimmermann** [comment]
Work-Benefit tradeoff too small.
