### ISSUE TITLE
[Spawn] /spawn and /setspawn issues

### ISSUE THREAD

**Issue by Stixil** [erikzimmermann/WarpSystem-IssueTracker#330]
After having updated to the newest version of WarpSystem and uninstalled EssentialsX-2.17.2.0, /spawn, /warpsystem:spawn, and /setspawn do not seem to work properly. 

/warpsystem:spawn says the command is unknown even though it appears in tab-complete
/warpsystem:setspawn is missing some options in the GUI.

The weird delay between joining the server and being warped to the destination is back as well, which is working perfectly with EssentialsX installed. Once uninstalled, it no longer works correctly.

Attached are 3 screenshots and a GIF video of what I'm trying to describe. Sadly there are no console errors for the bug. Thanks!

![2020-05-17 15-04-23](https://user-images.githubusercontent.com/53889383/82157558-34de2200-9850-11ea-956a-bbe8e0a9bcf1.gif)

![2020-05-17_15 05 44](https://user-images.githubusercontent.com/53889383/82157516-eb8dd280-984f-11ea-9e15-5045d452df7b.png)

![unknown](https://user-images.githubusercontent.com/53889383/82157460-9225a380-984f-11ea-9353-4f469f147965.png)

![unknown (1)](https://user-images.githubusercontent.com/53889383/82157461-92be3a00-984f-11ea-8c4c-f08df51551f7.png)

**Comment by erikzimmermann** [comment]
Todo: 
* Send message to admins if they try to use /spawn and the spawn is only configured for joins that this must be toggled to "Local" or "Global".
* Spawn: setSpawnLocation (priority=low)
* Bungee tp: setSpawnLocation (priority=Highest)

**Comment by erikzimmermann** [comment]
Third picture still in v4.2.6
