### ISSUE TITLE
/tp TabComplete and cross-server broken

### ISSUE THREAD

**Issue by Stixil** [erikzimmermann/WarpSystem-IssueTracker#333]
I am unable to TabComplete properly, or across servers with WarpSystem.

I think this is related to my previous issue #330. Without EssentialsX, I am unable to TP to players on other servers ("This player is not online!"), and tabcomplete does not work properly.

When on different servers, it should show the tabcomplete for all players online on the bungee network. Instead it only shows local players, and tabcompleting always completes the top player's username, regardless of what characters were typed in the chat to update the tabcomplete.

![1](https://user-images.githubusercontent.com/53889383/82356129-308d4280-99d1-11ea-9feb-54950ac50a7a.PNG)
![2](https://user-images.githubusercontent.com/53889383/82356140-32570600-99d1-11ea-82e3-9c2a53ef6ee9.PNG)
![3](https://user-images.githubusercontent.com/53889383/82356145-3420c980-99d1-11ea-855e-c6c6e8d53834.PNG)

**Comment by erikzimmermann** [comment]
Did you install my WarpSystem on your Bungee?

**Comment by Stixil** [comment]
Yes, it is installed on Bungee and Paper. Version 4.2.5 on all.
