### ISSUE TITLE
Personal Warps (/pw) dissapearing still

### ISSUE THREAD

**Issue by TheKlarence** [erikzimmermann/WarpSystem-IssueTracker#334]
I am filing this report on behalf of my boss, so I might not be the most experienced with this.

Although a recent bug fix was made for players' personal warps disappearing for no reason, I found that personal warps still disappear daily.
For example, I set my own personal warp (/pw) with the GUI two nights ago (Sunday night). Last night (Monday), when attempting to use the personal warp (/pw), it was missing from the GUI and I had to set it again. Several other players on the server have reported similar issues with the plugin, even after the server was updated to the patched version of the plugin.

I expected the personal warps to remain set from one night to the next.
According to the owner of the server, any economic cost, such as a time expiration or a fee per warp, is set to false. I can provide the whole config if you'd like, but this is the line he mentioned was important when I asked how the expiration time was set.
 #Disables all types of costs, active time selector, teleport costs
    Economy: false

This came after the bug fix that was released in the last plugin update.

**Comment by erikzimmermann** [comment]
Thank you for your report. I need some additional information:
- Does your network include a BungeeCord?
    - If so, did you install my plugin on your BungeeCord?
    - If not, please open the PlayerWarpConfig.yml and check if you disabled the BungeeCord option.

**Comment by TheKlarence** [comment]
Our network has a bungeecord.
The boss says he installed the plugin “correctly”, so I assume he installed it on our bungeecord. It did work well besides the warps deleting, so this is most likely the case.
Also, the option is enabled.

**Comment by erikzimmermann** [comment]
Thank you. I will check this asap. Please join my [discord server](https://discord.gg/4eVAhKz) for latest dev builds. And please add me on Discord (CodingAir # 0281) for some optional hotfixes.

**Comment by erikzimmermann** [comment]
@TheKlarence  If you edit your pwarp: how do you configure your pwarp ingame (editor GUI)?

**Comment by erikzimmermann** [comment]
This issue might be appear one more time. But this must be fixed after a recreation of a warp.
