### ISSUE TITLE
Random Teleport Buy

### ISSUE THREAD

**Issue by InFiniityxSweety** [erikzimmermann/WarpSystem-IssueTracker#336]
If you want to buy a RandomTp it says: 
Do you want to buy a random teleportation for 500 coin (s)? [Yes : No]
If you move the mouse over the yes or no, it says >> click <<
The problem is that you can't click on it there.

**Comment by erikzimmermann** [comment]
Please contact me on Discord (CodingAir#0281). I need some additional information.

**Comment by erikzimmermann** [comment]
Linked to #346
