### ISSUE TITLE
[GlobalWarps] gwarp betweeen servers takes player to last known location on target server

### ISSUE THREAD

**Issue by troykay** [erikzimmermann/WarpSystem-IssueTracker#356]
Global warps that travel between servers will take a player to the last known spot on the target instead of the global warp point. 

1. Create a global warp called 'testwarp' on Server B.
2. Go to Server A.
3. Create a portal to 'testwarp' or /gwarp testwarp.
4. You'll be taken to your last known spot on Server B. 
5. Issue '/gwarp testwarp' and you'll be taken to the right location.

I would expect to be taken to the global warp point, not the last known spot.
 
Behaviour exists in 4.2.5 and 4.2.5_hotfix.

If you want access to the Bungee network where this can be witnessed, just let me know.

**Comment by Parthodys** [comment]
> Please contact me on Discord (CodingAir# 0281).

Was there a solution to this one? Having the same issue still.
