### ISSUE TITLE
Lore Icons bug

### ISSUE THREAD

**Issue by xxJesuliiEU** [erikzimmermann/WarpSystem-IssueTracker#364]
When you change the lore of an icon in the ActionIcons.yml and you restart server, nothing happend, same lore and if you want to edit it in the game, you have a limit, so its impossible to configure that feature well

**Comment by erikzimmermann** [comment]
Sorry for my very late response. When you edit memory data of my plugin you need to reload by `/ws reload false`. You need `false` since you don't want to save the current data which would overwrite your lore changes.
