### ISSUE TITLE
[WarpSystem] Ability to restrict which worlds/servers allow destinations

### ISSUE THREAD

**Issue by troykay** [erikzimmermann/WarpSystem-IssueTracker#366]
Initially, I was looking for the ability to prevent players from creating warps pointing to a specific world. 

_(My particular use case was this: I have a resource world and some temporary miniworlds where I don't want players to create destinations.)_

Thinking about it further, I think the ability to control which worlds (i.e. Multiverse, etc) or servers (BungeeCord) allow destinations in general would be valuable. 

It could be done with permissions which are true by default, and a permission check.  Something like:

     warpsystem.destinations.<server> = true (default)

(I'm not sure how you feel about setting a permission to false to negate permissions.)

If the world/server distinction is important, or if the combination is important (for example, you have multiple servers with multiple worlds), you could do something like: 

    warpsystem.destinations.<server>.<world> = true (default)

And then if I wanted to deny destinations to a server globally, just set it to false.  It could be overridden on a per group or per player basis by resetting the permission node to true.

If you wanted to make it a more modular version, add the destinations node to each of the modules:

    warpsystem.playerwarps.destinations.<server> = true (default)
    warpsystem.simplewarps.destinations.<server> = true (default)
    warpsystem.globalwarps.destinations.<server> = true (default)
    warpsystem.warpsigns.destinations.<server> = true (default)

**Comment by erikzimmermann** [comment]
This can be done by permission plugins.
