### ISSUE TITLE
Plugin message exception <NPE>

### ISSUE THREAD

**Issue by Stixil** [erikzimmermann/WarpSystem-IssueTracker#397]
**Describe the bug**
This error clogs up the logs frequently and I'm not sure the cause or how to reproduce it. It looks like it might happen on player join but I'm not positive.

**To Reproduce**
1. I'm running on Paper-83 version 1.16.1.
2. There are no errors printed in the chat, but the console is spammed with these at what seems like every player join event.

Stacktraces here: https://pastebin.com/m2tsCfSr

**Comment by erikzimmermann** [comment]
Already fixed. Gonna upload a hotfix soon!

**Comment by Stixil** [comment]
Great, thanks!
