### ISSUE TITLE
[Commands] Tab completion on commands

### ISSUE THREAD

**Issue by TerminatorXman** [erikzimmermann/WarpSystem-IssueTracker#405]
**Is your feature request related to a problem? Please describe.**
i would like so much the feature that you can tab player names with autocompletition in commands such as /tpa, etc.

**Describe the solution you'd like**
i would like so much the feature that you can tab player names with autocompletition in commands such as /tpa, etc.

**Describe alternatives you've considered**
idk, is an easy one to do...

**Additional context**

**Comment by CodingAir** [comment]
# Note for myself
Use BungeeCord displaynames on bungee wide tab completions

**Comment by erikzimmermann** [comment]
Already implemented. Do you use a plugin which cancels tab completions?

**Comment by divios** [comment]
Hi! Just wanted to say that for me it isn't working either, at least in the last free version

**Comment by erikzimmermann** [comment]
Please use my latest dev build from my Discord server. The invitation link can be found on my SpigotMC Page.
