### ISSUE TITLE
WarpSystem v4.2.7 generated an exception whilst handling plugin message

### ISSUE THREAD

**Issue by TKwSni** [erikzimmermann/WarpSystem-IssueTracker#411]
**Describe the bug**
Error on console on player login:

https://hastebin.com/vugifexojo.bash

**To Reproduce**
1. Upgrade from 4.2.4 to 4.2.7
1. Log in

**Comment by erikzimmermann** [comment]
Already fixed in dev builds. Gonna upload a new release next week.
