### ISSUE TITLE
[WarpGUI] Inventory doesn't close after clicking a warp

### ISSUE THREAD

**Issue by OfficialTheosis** [erikzimmermann/WarpSystem-IssueTracker#423]
The title pretty much says it all. Just updated the plugin to version 4.2.7 to 4.2.8 and this happened. No big deal, but definitely not an intention (I hope lol). :)

**Comment by erikzimmermann** [comment]
Do you mean my WarpGUI?

**Comment by OfficialTheosis** [comment]
Yeah
