### ISSUE TITLE
Small language bug

### ISSUE THREAD

**Issue by OfficialTheosis** [erikzimmermann/WarpSystem-IssueTracker#424]
**Describe the bug**
When teleporting to a player, the message sent to the player who teleported seems to be the "Teleported_To" string from the language YML file. This isn't a problem on its own, but the fact that the placeholder "%warp%" is being substituted for a player name seems to result in the underscores from said player's name to be removed from the message. The attached screenshot shows this.

**To Reproduce**
Teleport to a player and have the "Teleported_To" string in the lang YML use the "%warp%" placeholder.

**Expected behavior**
The player's name should be displayed correctly (i.e. underscores should be included if there are any)

**Screenshots**
![1](https://user-images.githubusercontent.com/26799016/88114049-f6941480-cbaa-11ea-97f6-6449f2fa25e0.png)

**Additional context**
N/A

**Comment by erikzimmermann** [comment]
Note: Remove translation of underscores in general. With #444, warps support spaces in their names.
