### ISSUE TITLE
[Name] <Short description>

### ISSUE THREAD

**Issue by OfficialTheosis** [erikzimmermann/WarpSystem-IssueTracker#425]
**Is your feature request related to a problem? Please describe.**
Sort of. The usage messages for commands should be configurable. I have a set colour scheme on my server for messages, and the fact that these messages aren't customisable separates them from the colour scheme, which is a little bit frustrating.
![1](https://user-images.githubusercontent.com/26799016/88114403-aff2ea00-cbab-11ea-9551-fe6318728186.png)

**Describe the solution you'd like**
Allow the usage messages for commands to be configurable in the language YML files.

**Describe alternatives you've considered**
Can't think of any lol. :(

**Additional context**
N/A

**Comment by erikzimmermann** [comment]
With v4.2.8 you can edit usage suggestion colors with `/ws options` or in your Config.yml

**Comment by OfficialTheosis** [comment]
Ah brilliant, thank you! :)
