### ISSUE TITLE
[Bungee teleports] Empty messages cause write errors

### ISSUE THREAD

**Issue by Sylensky** [erikzimmermann/WarpSystem-IssueTracker#429]
**Describe the bug**
I experienced it randomly within the latest 4.2.8 release. I haven't noticed any issues related to this error report so far but iam looking for any.

**To Reproduce**
1. use latest warpsystem release
2. install it on all servers
3. observer the waterfall logs

**Expected behavior**
no error logs appearing

**Screenshots**
[bungeeerror.txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/4991125/bungeeerror.txt)

**Additional context**
Sorry this vague bug report but thats all i got for now.

**Comment by Davie3** [comment]
Have also been observing the same bug with Waterfall (v366) on latest 4.2.8. It seems to happen when I enter a portal that is linked to go to another server in the network. The destination being the [Server](https://github.com/CodingAir/WarpSystem-IssueTracker/wiki/Server-(require-BungeeCord)) itself to be clear and not a warp point. It does still transport me to the server, though.

[waterfallerror.txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/5012715/waterfallerror.txt)

**Comment by jinglyjangles** [comment]
I'm seeing this on Bungeecord & Paper setup as well.
