### ISSUE TITLE
[Portals] Portals do not porperly save

### ISSUE THREAD

**Issue by dorsax** [erikzimmermann/WarpSystem-IssueTracker#432]
**Describe the bug**
After a reboot of the server, the `destination:teleportations-time` of a portal resets  to 3 seconds.

**To Reproduce**
1. Edit a portal 
2. Change the value of the destination's timer
3. Save the portal
4. it works!
5. reboot the the server
6. The value is set back to 3 seconds.

**Expected behavior**
No set back.

**Additional context**
Running WarpSystem v4.2.8 on PaperSpigot 1.15.2

**Comment by erikzimmermann** [comment]
Same as in #430 -> Closing
