### ISSUE TITLE
Server Crash Log

### ISSUE THREAD

**Issue by Stixil** [erikzimmermann/WarpSystem-IssueTracker#451]
**Describe the bug**
Instant server crash with large stacktrace.

**To Reproduce**
Unsure how to reproduce.

**Additional context**
https://mcpaste.io/ff53cab339a2914a

**Comment by erikzimmermann** [comment]
Seems like a bug from Bukkit/Spigot/Paper, because this error has been thrown by a cernal procedure.

**Comment by Stixil** [comment]
Testing now with WS disabled, I will let you know.
