### ISSUE TITLE
WarpSystem uses outdated PlaceholderAPI methods

### ISSUE THREAD

**Issue by Andre601** [erikzimmermann/WarpSystem-IssueTracker#453]
**Describe the bug**
WarpSystem is using outdated methods from PlaceholderAPI which no longer work as of 2.10.9 and only print a warning.

Warnings such as `[PlaceholderAPI] warpsystem is attempting to unregister placeholders through the PlaceholderAPI class which is no longer supported!` can be encountered on shutdown.

**To Reproduce**
1. Use latest WarpSystem and PlaceholderAPI 2.10.9

**Expected behavior**
WarpSystem should use the recommendet methods.

**Screenshots**

**Additional context**

**Comment by erikzimmermann** [comment]
Please try a hotfix from my discord (https://discord.gg/4eVAhKz).
