### ISSUE TITLE
[Ping Handler] Ping Error on Bungeecord

### ISSUE THREAD

**Issue by Davie3** [erikzimmermann/WarpSystem-IssueTracker#454]
**Describe the bug**
Wanted to test the fix for #429 in v4.2.9 but there appears to be a bug with the Ping Handler on Bungeecord/Waterfall. Tested on Bungeecord v1530 and Waterfall v370 with the same behavior. Posted logs below.

**To Reproduce**
1. Execute `/portals edit`
2. Run into a Portal with the [Destination Type Server](https://github.com/CodingAir/WarpSystem-IssueTracker/wiki/Server-(require-BungeeCord))
3. Observe Ping Handler errors in Bungeecord/Waterfall console
4. Observe the Destination stuck at "Pinging..." even after refreshing

**Expected behavior**
For the ping to go through to the Networked Server to link the portal as a destination.

**Screenshots**
![bungeecord ping error](https://user-images.githubusercontent.com/536044/90592365-43fba580-e19a-11ea-9ba2-8a4eb230b402.png)

**Additional context**
Waterfall Logs: [bungeecord ping error.txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/5094001/bungeecord.ping.error.txt)

**Comment by erikzimmermann** [comment]
Entire BungeeCord connection is affected.
