### ISSUE TITLE
Console errors after latest update that forces permissions on new cooldowns

### ISSUE THREAD

**Issue by StenaCS** [erikzimmermann/WarpSystem-IssueTracker#456]
https://pastebin.com/sfLxrcjd

**Comment by erikzimmermann** [comment]
Already fixed with #455

**Comment by StenaCS** [comment]
I am using the latest spigot and am getting these errors. On spigot it shows #423 so where is #455?

**Comment by StenaCS** [comment]
https://pastebin.com/L0N2jLuL with ever new player that joins.

**Comment by erikzimmermann** [comment]
Please contact me on Discord (CodingAir # 0281).

EDIT: #455 isn't uploaded yet. I'm on it.
