### ISSUE TITLE
[MarksAPI Support] Could you please add support for MarksAPI?

### ISSUE THREAD

**Issue by yueyinqiu** [erikzimmermann/WarpSystem-IssueTracker#469]
**Feature description**  
Add support for MarksAPI - Just implement a marks provider which can provider the warps as marks.  
It's a new plugin written by myself.

Its purpose is to put all the plugins' marks together, so I'm here creating the issue.

**How the feature is useful**  
I think it will be better to paste the link than describe here: [https://www.spigotmc.org/resources/83087/](https://www.spigotmc.org/resources/83087/).

**Other alternative idea**
Open an API that other plugins can get the warps, then I or someone else can also link this plugin with MarksAPI.

If you won't add this feature, please tell me the reason so I can improve it.  
Sorry for my poor English. If there is any ambiguity, please leave a comment.

**Comment by erikzimmermann** [comment]
I already have an import function for warps of essentials and I don't see major advantages for me and my users here. Sorry
