### ISSUE TITLE
BungeeCord Dimension Support

### ISSUE THREAD

**Issue by Brickgard** [erikzimmermann/WarpSystem-IssueTracker#470]
An amazing premium feature for your warp system plugin would be to provide the option to redirect vanilla portals to alternative BungeeCord-connected servers.

For example, and for sure the simpler of the two: a config option to send End Portals to a different server instead of the internal _the_End dimension as vanilla Minecraft does.  Then have that world's End Portals send the player back to the original world.

My search for such a feature has only resulted in many "it's possible" and "Yeah, someone could do that" but no actual solutions available.
If you want a major value-adding element, handling nether portals in a similar way (to allow larger survival servers to separate their overworld and nether worlds across different servers) would be incredibly impressive and helpful!

**Comment by erikzimmermann** [comment]
Hi, thank you for your contribution.

**Comment by erikzimmermann** [comment]
## Todo
* Portal-Types: Nether, End(, End-Gateway?)
