### ISSUE TITLE
Global warps suddenly break and stop working

### ISSUE THREAD

**Issue by ghost** [erikzimmermann/WarpSystem-IssueTracker#475]
Randomly throughout the day, warpsystem's globalwarps will stop working and cease to work until the servers been restarted. This has been happening on and off for the past week and I have no idea how to reproduce it. It seems to just happen at random.

Here's the only Error Log we've been able to find related to it : https://pastebin.com/1UzTGvVL
I'm using version 4.2.11 on Paper 1.15.2 as well as on Bungeecord

**Comment by ghost** [comment]
Can you please fix this? I payed money for this plugin and this has been ruining my server.

**Comment by erikzimmermann** [comment]
Sure! I’ll fix this directly when I’m home on my pc. This will be the 3rd October.

**Comment by ghost** [comment]
Any updates on this? I'm still experiencing these issues and I'm having to restart my server up to 3 times a day just to fix it.
