### ISSUE TITLE
Json Component Error on /tpa

### ISSUE THREAD

**Issue by RedZephon** [erikzimmermann/WarpSystem-IssueTracker#489]
**Describe the bug**
When you request a teleport using the /tpa command, you get disconnected with a can't convert json to component error.

**To Reproduce**
1. Run /tpa <playername> or /tpahere <playername>
2. Get Disconnected

**Expected behavior**
You should be able to accept the teleport request without getting Disconnected

**Screenshots**
![Screen_Shot_2020-10-29_at_12 17 56_AM](https://user-images.githubusercontent.com/16528824/97764939-82cca680-1acd-11eb-977d-87c178d398b5.png)

**Additional context**
Only the person getting the request (accept or deny) gets disconnected. Not the person sending the request. Restarting the server temporarily fixes the issue but it returns some hours later.

**Comment by erikzimmermann** [comment]
Same as #488
