### ISSUE TITLE
Anomaly with Tpa requests

### ISSUE THREAD

**Issue by JustJP2K** [erikzimmermann/WarpSystem-IssueTracker#496]
Some players cannot tpa to others, it will simply state to the receiving person when he tries to accept, either by pressing the accept button or tpying /taccept: you dont have any pending tpa requests from [player]. 
It is on a single server, no bungeecord. 
Since its an anomaly and only happens to a few players, this bug is really weird.

**Comment by erikzimmermann** [comment]
Only happens with requests that are sent to shortened player names.

**Comment by JustJP2K** [comment]
Will there be a fix for this so you can tp to players with nicknames?

**Comment by erikzimmermann** [comment]
Should be fixed with v4.2.12
