### ISSUE TITLE
Per World Warpdelay

### ISSUE THREAD

**Issue by Sylensky** [erikzimmermann/WarpSystem-IssueTracker#499]
**Is your feature request related to a problem? Please describe.**
It kind of is related to a feature conflict that i came across by building a portal that the player jumps in and therefor the delay has to be zero otherwise he keeps falling and interrupt the teleporting process.
However this portal leads to another world where it shouldn't be possible to warp without a delay (PvP, Combat).

**Describe the solution you'd like**
A solution that let the worlds manually configure in the config file where delays are active and where not would solve this conflict.

**Describe alternatives you've considered**
An alternative would be using a whole other plugin just for that specific case which would be not the best option in my opinion.

**Comment by erikzimmermann** [comment]
You can use the destination options for that. Just go into the portal editor to the destination page and right click the header item. Then set the delay to 0 and you're done.
