### ISSUE TITLE
[WarpGUI] ActionIcons.yml order issue

### ISSUE THREAD

**Issue by terbin** [erikzimmermann/WarpSystem-IssueTracker#501]
**Describe the bug**
When creating ActionIcons  they appended to ActionIcons.yml this can cause issues on restart of the server when an Icon is moved into a Page (where the Page was created after the Icon and therefore the Icon is above the Page entry in ActionIcons.yml).
WarpSystem upon restart of the server first loads the icons but has not loaded the Page yet, therefore it places the Icons in the main /warps menu. 

If an icon already exists in the same slot in the Page as in the main /warps menu the icon is not shown and is deleted from ActionIcons.yml on next save.

**To Reproduce**
1. create a new ActionIcon
2. create a new Page
3. restart the server
4. move the ActionIcon, using the GUI, into the newly created Page
5. restart the server
5. The Icon will be listed before the Page in ActionIcons.yml so the Icon will be placed in the main /warps menu or deleted, depending on existing icons there.

**Expected behavior**
Order of addition of Pages and Icons should not matter in the GUI, should be evaluated after complete ActionIcons.yml is loaded.

**Additional context**
Workaround: edit ActionIcons.yml and move all entries where **isPage: true** to the top

**Comment by terbin** [comment]
Using Paper 1.12.2 and WarpSystem Premium 4.2.11

**Comment by terbin** [comment]
Does the closing mean it will be fixed in a future version?
It is still an issue in 4.2.12 Premium.

**Comment by erikzimmermann** [comment]
It's tagget with milestone [5.0.0](https://github.com/CodingAir/WarpSystem-IssueTracker/milestone/36) which means it will be fixed in v5.0.0 (planned ETA: 28th or 29th January).
