### ISSUE TITLE
[Portals] Items from setting teleport blocks are kept in inventory after timeout

### ISSUE THREAD

**Issue by AlexanderMandera** [erikzimmermann/WarpSystem-IssueTracker#502]
**Describe the bug**
The items from setting teleport blocks in the hotbar are kept in inventory after rejoining from a timeout.

**To Reproduce**
1. /portals create
2. Edit teleport blocks
3. Place some blocks
4. Timeout (idk if a disconnect is enough) :smile: 
5. Join again
6. Blocks are kept in hotbar

**Expected behavior**
Remove the items from the hotbar or restore the portal session after joining in x minutes to reuse the portal blocks again.

**Screenshots**
![image](https://user-images.githubusercontent.com/3356015/100487013-ee268a00-3106-11eb-9f60-93f9c5d2e9a0.png)

**Additional context**
None

**Comment by erikzimmermann** [comment]
Other hotbar guis has been fixed too.
