### ISSUE TITLE
Bungee-wide teleport world/coordinate support

### ISSUE THREAD

**Issue by Brickgard** [erikzimmermann/WarpSystem-IssueTracker#520]
Hoping to be able to have WarpSystem handle teleports between servers while also taking input for destination server, world, and coordinates.

For example:
`/tp <player> <x> <y> <z> <world> <server>`
(With world and server being new, optional arguments to send a player to that specific world, or a specific world within the destination server)

This allows a more flexible option/alternative beyond pre-set warp locations, especially when interacting with other plugins.

**Comment by erikzimmermann** [comment]
Final command syntax: `/tp [player] [<player> | [<x> <y> <z>] [<yaw> <pitch>] [<server> [world] | <world>]`
