### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by 849025143** [erikzimmermann/WarpSystem-IssueTracker#554]
Shortcuts
——————
Add a target command
Like:
Server A ----TP----> Server B
ServerB execute command，Like /suicide

**Comment by erikzimmermann** [comment]
An automatically executed command after a server switch?

**Comment by 849025143** [comment]
> An automatically executed command after a server switch?

yes

**Comment by erikzimmermann** [comment]
This does not fit any of my plugin's scopes. Maybe a PlayerJoin plugin provides this functionality.

**Comment by 849025143** [comment]
> This does not fit any of my plugin's scopes. Maybe a PlayerJoin plugin provides this functionality.

Island server.
I think they can use the / is command and go back to their island.
Instead of going to the server spawn.
