### ISSUE TITLE
[Random TP] Add more option for setting up Random TP

### ISSUE THREAD

**Issue by Andre601** [erikzimmermann/WarpSystem-IssueTracker#564]
**Is your feature request related to a problem? Please describe.**
One specific issue is, that you can't define a Random TP for ANOTHER world than the one you're currently in (i.e. you use a block in spawn, to rtp in survival, but it only rtp in spawn)

**Describe the solution you'd like**
It would be nice, if the RTP could receive additional options. I've made a list below.

*Other interaction types*
It would be nice to have different interaction types. Like you place down a preasure plate that the player would then step on to teleport, instead of clicking on some block.

*Decorations*
RTP could have similar options to portals as in particle effects and similar.

*Allow different world for RTP destination*
From what I found out does the RTP only allow random teleportation within the same world (At least for interactable blocks) which is limiting.

**Describe alternatives you've considered**
Only alternative(s) would be a simple portal which isn't that nice either...

**Additional context**

**Comment by erikzimmermann** [comment]
Already added
