### ISSUE TITLE
Give /tphere its own permission

### ISSUE THREAD

**Issue by StealWonders** [erikzimmermann/WarpSystem-IssueTracker#573]
Add a new permission that prevents/grants players access to teleport players to themselves.
Anyone with the normal teleport permission can teleport anyone (even admins) to themselves even though this is not the preferred behavior of my server.

→ Split teleport to and teleport here behaviors into two separate permissions.

Optional: a weighted permission system so that x rank can teleport y ranks below them but no rank over them. (perhaps premium idc)

**Comment by erikzimmermann** [comment]
Why should players be able to teleport all other player to them? Isn't that an admin only function?

**Comment by StealWonders** [comment]
> 
> 
> Why should players be able to teleport all other player to them? Isn't that an admin only function?

On a survival or minigame server yes. I run a creative server that allows anyone to teleport to anyone (if teleport isn't disabled).
People shouldn't be able to teleport others to themselves without any confirmation by the other player (can be abused pretty hard).

**Comment by erikzimmermann** [comment]
Then what about a new command like /tpto? I think that might be much better.

But still new permissions for /tphere and /tpto.

**Comment by StealWonders** [comment]
/tp is alot simpler than /tpto...

Is there any reason why you are against adding a simple permission that extends the /tp command featureset?

**Comment by erikzimmermann** [comment]
It's just easier for everyone to allocate permissions.

**Comment by erikzimmermann** [comment]
I'll add /tpto with a different permission and give /tphere a new permission.

You can change `/tpto` to `/tp` later in the Commands.yml.

**Comment by erikzimmermann** [comment]
Update. Gonna use /tp for tpto.
