### ISSUE TITLE
Console spam after latest update

### ISSUE THREAD

**Issue by mellowism** [erikzimmermann/WarpSystem-IssueTracker#575]
Hi,

Waterfall console gets spammed with the following message after latest update: https://pastebin.com/PswZ4Qfi 

Latest Waterfall (395) and WarpSystem (5.0.1)

Console for servers have some minor spam: https://pastebin.com/xYLgcxKP

**Comment by erikzimmermann** [comment]
Fixed, pls download a new jar.
