### ISSUE TITLE
Different Tp commands

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-IssueTracker#59]
Tptoggle - Allow/Deny force teleports
TpaToggle - Allow/Deny teleport requests
Tpa - TeleportRequest (TR) to a player (Dest: Other)
Tphere - TR to a player (Dest: Me)
Tphereall - TR to all players (Dest: Me)
Tpall - Teleport all players to me

Permissions:
TpToggle: WarpSystem.Use.TeleportCommand.TpToggle
TpaToggle: WarpSystem.Use.TeleportCommand.TpaToggle
Tpa: WarpSystem.Use.TeleportCommand.Tpa
TpHere: WarpSystem.Use.TeleportCommand.TpHere
TpHereAll: WarpSystem.Use.TeleportCommand.TpHereAll
TpAll: WarpSystem.Use.TeleportCommand.TpAll

**Change current tp command permission to: WarpSystem.Use.TeleportCommand.Tp**

~BungeeCord access: WarpSystem.Use.TeleportCommand.BungeeAccess~

**Comment by merlinshaw** [comment]
Looking forward to this!
