### ISSUE TITLE
[Icons] Delete Icons from categorie

### ISSUE THREAD

**Issue by Schlabunke** [erikzimmermann/WarpSystem-IssueTracker#597]
**Describe the bug**
Problems with categories in the warp menu. You can´t delete icons from a categorie. If you try to delete it, the icon is still in categorie.

**To Reproduce**
1. Create an Icon on the first page
2. Move the icon to a categorie
3. You can´t delete it

**Discord contact**: Schlabunke #4964

**Comment by pupshadow** [comment]
I can say that this is a real issue on my server as well. I am also having issues where the button for setting destinations isn't working there is no button for it anymore.

**Comment by erikzimmermann** [comment]
Works fine for me.
