### ISSUE TITLE
[Portals] System crashes on dead

### ISSUE THREAD

**Issue by dorsax** [erikzimmermann/WarpSystem-IssueTracker#601]
**Describe the bug**
When you die while being in an hotbar-editor (like set spawn or set portal blocks), you will be dead, dropping those items. If you respawn, you will be stuck in the editor mode until the server is restarted. Also, the items can be collected by any other user around you.

**To Reproduce**
1. /portals edit
2. Go into the set spawn for the portal
3. Die by a creeper because you were to dumb to go into creative

**Expected behavior**
I don't know, like, prevent users from being that stupid? And/or prevent death in this mode/don't drop items on death/cancel mode after death (because afterwards nothing really worked at all)

**Additional context**
Version 5.0.1 Premium

**Discord contact**: you knwo me ;)

**Comment by erikzimmermann** [comment]
Waiting for new CodingAPI update.
