### ISSUE TITLE
[Permissions] default behavior

### ISSUE THREAD

**Issue by dorsax** [erikzimmermann/WarpSystem-IssueTracker#604]
**Is your feature request related to a problem? Please describe.**
We see frequent support questions where to enable permissions as a lot of users expect it to be enabled by default. This might arise the question how an admin can configure the plugin at startup, so maybe the configuration might be available to operators (/op)

**Describe the solution you'd like**
In fresh installations, enable permissions by default and/or ask it on the setup assistent.

**Comment by erikzimmermann** [comment]
Bump
