### ISSUE TITLE
[Portals] Portals sometimes disappear when the server stops

### ISSUE THREAD

**Issue by fof1092** [erikzimmermann/WarpSystem-IssueTracker#615]
**Describe the bug**
The portals sometimes disappear at a server stop. 
The block-break animation of the portal is visible.

**To Reproduce**
1. Create a (Nether) portal (Our portal points to a gwarp on another bungeecord server)
2. Stop the server

**Expected behavior**
The portals do not disappear...

**Additional context**
[Serverlog.txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/6387145/Serverlog.txt)

**Discord contact**: F_o_F_1092#9467

Thanks for the great plugin! 👍

**Comment by erikzimmermann** [comment]
Hi, this might be an error of your Minecraft server. I can't really do something here, sorry.

https://bugs.mojang.com/browse/MC-146279
