### ISSUE TITLE
[RTP] Async catch when getting a chunk

### ISSUE THREAD

**Issue by Shixpy** [erikzimmermann/WarpSystem-IssueTracker#622]
When I am trying to use rtp go command it is sending this error to the console.

![image](https://user-images.githubusercontent.com/84266761/118391256-0b5efe80-b63c-11eb-9af1-e7a148006236.png)

Shixpy#3222

**Comment by erikzimmermann** [comment]
This depends on the PaperLib I use there. Please try to use Paper first.
