### ISSUE TITLE
Velocity proxy syncro.

### ISSUE THREAD

**Issue by damien34760** [erikzimmermann/WarpSystem-IssueTracker#623]
Hi, 

I'm using two velocity proxy (v1.1.5) with two paper (v1.8) server in the backend.
I'm using the WarpSystem [5.0.2_Hotfix-1] version on both of my machine.

I got an error with the global warps between the two proxy : 

Player1 login to the backend using Proxy1. He create a global warp name "debug" and he can see it or use it. No problem.

Now, player2 login using Proxy2. If he do a global warps list. He cant see the global warp "debug" and now if the first player try to list the global warp, he will see nothing. He cant use tp on that warp and also can't create a new global warp with the name "debug". The plugin said that it already exists.

Thanks you :)

**Comment by erikzimmermann** [comment]
Fixed by #624
