### ISSUE TITLE
Issue with messages.yml

### ISSUE THREAD

**Issue by Zethi** [erikzimmermann/WarpSystem-IssueTracker#625]
**Is your feature request related to a problem? Please describe.**
It is really a problem to make the guis have a good design in terms of colors, it is impossible to make a good color combination for servers with 2 or 3 colors.

**Describe the solution you'd like**
A solution would be to redo the messages.yml format.

**Describe alternatives you've considered**
Another solution could be to separate the names of the guis from the normal messages.

**Additional context**
![Screenshot_734](https://user-images.githubusercontent.com/78290683/119427771-a2315800-bcd9-11eb-88cd-980b1fabb05f.png)
![Screenshot_735](https://user-images.githubusercontent.com/78290683/119427773-a493b200-bcd9-11eb-95ce-c3beb0a24257.png)

**Discord contact**: Zeth#1090

**Comment by joshwenke** [comment]
This would be great! It is currently not possible to customize every message in the plugin.
