### ISSUE TITLE
[Back] Restrict the use of "/back" to certain worlds

### ISSUE THREAD

**Issue by clementinise** [erikzimmermann/WarpSystem-IssueTracker#627]
**Is your feature request related to a problem? Please describe.**
Players can "/back" in a world only accessible with a duel command, so if they "/back" in this world, they can disturb other players that are already in a duel.

**Describe the solution you'd like**
Give the possibility to restrict the use of "/back" to certain worlds. Create a permission that restrict players, like ``warpsystem.use.teleportcommand.back.<worlds>``

**Describe alternatives you've considered**
I think permissions is the best way to do it, so moderators of a minecraft server can "/back" somewhere players can't

**Additional context**
None

**Discord contact**: Clementinise#5530

**Comment by erikzimmermann** [comment]
moved to #727
