### ISSUE TITLE
ChatButtons will be logged to chat

### ISSUE THREAD

**Issue by dorsax** [erikzimmermann/WarpSystem-IssueTracker#634]
**Describe the bug**
Clicking on "hide" will throw a message to the chat:
![grafik](https://user-images.githubusercontent.com/56792918/123708994-99015100-d86c-11eb-9c9d-b22440ba996e.png)

**Additional context**
Paper 1.15.2 on WarpSystem 5.0.3-Hotfix-1-free

**Discord contact**: Pulsi_#6433

**Comment by Pulsih** [comment]
You can also contact me here

**Comment by erikzimmermann** [comment]
That shouldn't be present anymore. I've tested it. Do you maybe have multiple WarpSystem jars in your plugins folder?

**Comment by Kaesor** [comment]
I've the same problem, and i've only one WarpSystem jar in plugins folder.
I use bungee (waterfall), and the plugins is up to date.

Paper : 1.17.1 - 219
WarpSystem : v5.0.4

**Comment by erikzimmermann** [comment]
Kaesor: InteractiveChat

**Comment by erikzimmermann** [comment]
> You can also contact me here

Sorry for my late reply. Did you use any additional chat plugins (on your spigot or your proxy server)?

**Comment by erikzimmermann** [comment]
And for all of you: Do you also use my TradeSystem?

**Comment by Kaesor** [comment]
For me, i use other plugin (UltraCustomizer for exemple), but none make this error, and i use TradeSystem too.

**Comment by erikzimmermann** [comment]
Please bump if this isn't fixed in the latest version.

**Comment by CosmicHikari** [comment]
I have the same issue but when someone does /rtp buy and clicks yes.

They also don't get any warps given either even though they clicked yes to buy. I use xconomy and vault.


Edit: Spigot 1.19
