### ISSUE TITLE
Upgraded to 1.17.1:  java.lang.IllegalArgumentException: Can not set net.minecraft.world.entity.Entity field net.minecraft.world.item.ItemStack.w to net.minecraft.nbt.NBTTagCompoun    d

### ISSUE THREAD

**Issue by troykay** [erikzimmermann/WarpSystem-IssueTracker#637]
I upgraded from 1.17 to 1.17.1 last night.  This is the error I got:

`  1 java.lang.ExceptionInInitializerError                                                                                                                                       
2 ->>>>>>>at de.codingair.warpsystem.spigot.features.portals.utils.BlockHierarchy$Bounds.read(BlockHierarchy.java:139)                                                        3 ->>>>>>>at de.codingair.warpsystem.spigot.features.portals.utils.BlockHierarchy.read(BlockHierarchy.java:32)                                                                4 ->>>>>>>at de.codingair.warpsystem.spigot.features.portals.utils.Portal.read(Portal.java:122)                                                                               5 ->>>>>>>at de.codingair.warpsystem.spigot.features.portals.managers.PortalManager.load(PortalManager.java:85)                                                               6 ->>>>>>>at de.codingair.warpsystem.spigot.base.managers.DataManager.load(DataManager.java:59)                                                                               7 ->>>>>>>at de.codingair.warpsystem.spigot.base.WarpSystem.onEnable(WarpSystem.java:178)                                                                                     8 ->>>>>>>at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)                                                                                                9 ->>>>>>>at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)                                                                                 10 ->>>>>>>at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)                                                                                11 ->>>>>>>at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)                                                                                  12 ->>>>>>>at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)                                                                                 13 ->>>>>>>at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604)                                                                                        14 ->>>>>>>at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)                                                                                   15 ->>>>>>>at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995)                                                                                                16 ->>>>>>>at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)                                                                                         17 ->>>>>>>at java.base/java.lang.Thread.run(Thread.java:831)                                                                                                                 18 Caused by: java.lang.IllegalArgumentException: Can not set net.minecraft.world.entity.Entity field net.minecraft.world.item.ItemStack.w to net.minecraft.nbt.NBTTagCompoun    d                                                                                                                                                                          19 ->>>>>>>at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)                                       20 ->>>>>>>at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
 21 ->>>>>>>at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)                                                         22 ->>>>>>>at java.base/java.lang.reflect.Field.set(Field.java:793)                                                                                                           23 ->>>>>>>at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection$5.set(IReflection.java:234)                                                                24 ->>>>>>>at de.codingair.warpsystem.lib.codingapi.tools.nbt.NBTTagCompound.<init>(NBTTagCompound.java:30)                                                                   25 ->>>>>>>at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:88)                                                                       26 ->>>>>>>at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:77)                                                                       27 ->>>>>>>at de.codingair.warpsystem.spigot.features.portals.utils.BlockType.<clinit>(BlockType.java:14)                                                                     28 ->>>>>>>... 16 more  `

**Comment by troykay** [comment]
Here's the full log of the server startup: https://pastebin.com/YKY91wFh

**Comment by erikzimmermann** [comment]
Has the same source as #642
