### ISSUE TITLE
Teleport delay counts down when sinking in water

### ISSUE THREAD

**Issue by OfficialTheosis** [erikzimmermann/WarpSystem-IssueTracker#640]
**Describe the bug**
When sinking in water, and therefore moving, the teleport delay counter still ticks down instead of cancelling.

Since players might get annoyed with not being able to teleport while in water, perhaps add a boolean configuration option for whether or not sinking in water should cancel teleports.

**To Reproduce**
1. Go into deep-ish water and swim to near the top
2. Teleport somewhere (make sure there is a configured delay)
3. Observe as the teleport does not cancel despite the player sinking, and therefore moving

**Expected behavior**
The teleport should cancel, as the player is technically moving.

**Discord contact**: <name>#<id>
Theosis#0001

**Comment by erikzimmermann** [comment]
This is implemented intentionally since you cannot really stand still in water unless you're on the ground.

**Comment by OfficialTheosis** [comment]
> This is implemented intentionally since you cannot really stand still in water unless you're on the ground.

Yeah that makes sense, but perhaps a configuration option for it would be nice? Up to you though, it's not really a big deal. :)

**Comment by erikzimmermann** [comment]
Alright :D

But I'll implement that in a later version!
