### ISSUE TITLE
[Teleport] Serverübergreifender Teleport zu Playern

### ISSUE THREAD

**Issue by e7a-0-e7a** [erikzimmermann/WarpSystem-IssueTracker#646]
**Describe the bug**
Serverübergreifender Teleport zu Spielern funktioniert nicht

**To Reproduce**

1. Ich gebe /tp <Spielername> im chat ein
2. und wenn dieser Spieler nicht auf dem gleichen Server des Bungee ist wie ich dann bekomme ich die Nachricht das dieser Spieler nicht Online ist.

**Expected behavior**
Ich habe erwartet zu dem angegeben Spieler teleportiert zu werden

**Screenshots**

Angezeigte Teleport Möglichkeiten (Andere Server im Netzwerk werden angezeigt aber keine Spieler außer ich selbst)
![Screenshot_41](https://user-images.githubusercontent.com/87435355/127674691-611e828f-5c1c-4fa1-ae96-71ff91c8a426.png)

Befehl und Messageausgabe im Chat
![Screenshot_42](https://user-images.githubusercontent.com/87435355/127674704-ddc29a86-dd21-4f64-888e-63facf01a3c5.png)

Keine Fehlermeldung in der Konsole
![Screenshot_43](https://user-images.githubusercontent.com/87435355/127674715-808a8cc7-60c0-43e6-b3a4-0f2d2b6a7c14.png)

**Additional context**
Ich habe in Essentials alle TP Commands deaktiviert
Alle Server gestoppt, den Bungee als erstes gestartet, danach die Unterserver.

**Discord contact**: Rhaven#7208

**Comment by erikzimmermann** [comment]
Ist das WarpSystem auf deinem Bungee installiert?

**Comment by e7a-0-e7a** [comment]
Ja das ist auf dem Bungee selbst auch installiert.

**Comment by erikzimmermann** [comment]
Bitte melde dich einmal auf Discord bei mir per DM. CodingAir#0640

**Comment by erikzimmermann** [comment]
![image](https://user-images.githubusercontent.com/23747243/132328222-b9c2c0a5-2d2c-499e-9aef-9a083e3846bf.png)
