### ISSUE TITLE
Server not responding anymore after updating WarpSystem.

### ISSUE THREAD

**Issue by Paceski** [erikzimmermann/WarpSystem-IssueTracker#649]
**Describe the bug**
Server freezes after updating warpsystem.
**To Reproduce**
Update warp system. 

**Expected behavior**
Not freeze and work as expected as it was in older versinos.
**Screenshots**
https://gyazo.com/84d1ea0ec852339863f4c2ca6b3be349
**Additional context**

**Discord contact**: Pace 0001

If I delete warp system, it works all fine, I updated due to that annoying update checker that says 'null' and is big like fix that please.

**Comment by Paceski** [comment]
I don't use Paper by the way.

**Comment by erikzimmermann** [comment]
Would you send me the entire stacktrace? I can't do much without it, thanks!

**Comment by Paceski** [comment]
I am unable to anymore, but the error I sent (https://gyazo.com/84d1ea0ec852339863f4c2ca6b3be349) is the only thing I saw when I reported this, and now I am unable to reproduce this.

I ran Java 8, 1.8 server, with TacoSpigot.
When I updated warp system to latest it didn't even let me join after boot, and showed that thread error.

Sorry for this, if you want you can close, I don't use WarpSystem anymore anyways, and I don't have test server to test right now.
