### ISSUE TITLE
[slim custom portals orientation] 1 wide custom portal orientation locked to north-south

### ISSUE THREAD

**Issue by terbin** [erikzimmermann/WarpSystem-IssueTracker#653]
**Describe the bug**
I have an issue changing rotation of a 1 block wide, 2 blocks high portal - it always goes in the north south direction no matter what I do. There is no way, that I I could find, to create a 1 wide east-west portal.

**To Reproduce**
Create a 1 block wide custom portal, it will always face north-south, no matter what.

**Expected behavior**
If I look directly north or south and create a custom portal I expect the portal to be perpendicular to my charater's view

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/49982226/132463437-0bb1e769-70c8-4366-9efc-7ac960d97553.png)

**Comment by Parthodys** [comment]
Same issue here. I'm able to rotate it with WorldEdit, but it refreshes eventually into the same position.
One workaround I found was to place the nether portals first using WorldEdit, then create a portal using the custom portal block, seems to work.
