### ISSUE TITLE
[Velocity server portals] server portals don't work

### ISSUE THREAD

**Issue by Sergentval** [erikzimmermann/WarpSystem-IssueTracker#655]
**Describe the bug**
Server portal don't work on velocity

**To Reproduce**
1. Create 1 portal on 1 server under velocity
2. Create 2 portal on server 2 under velocity
3. See error on velocity console

**Expected behavior**
Send player to the server

**Screenshots**
![image](https://user-images.githubusercontent.com/40761828/133908291-749b72c4-b748-430f-afdc-f069dfbd262c.png)
![image](https://user-images.githubusercontent.com/40761828/133908304-737de1d5-01c3-413b-ae9c-e1c702ad3838.png)

**Additional context**

**Discord contact**: Sergent_val # 0117

**Comment by erikzimmermann** [comment]
Hi there. Please check your servers in your velocity.toml. There might be a syntax error
