### ISSUE TITLE
[Geyser-Floodgate] Cross-server teleports fail with Target Server not Found after a few minutes running

### ISSUE THREAD

**Issue by mattc4t** [erikzimmermann/WarpSystem-IssueTracker#659]
**Describe the bug**
I am running a bungee network and have successfully used WarpSystem 5.0.5.  After installing Geyser on the Bungee server and Floodgate on the proxy and spigot servers, I can initially use portals and teleports cross-server, but after a few minutes fail with an error, "The targer server is not online".  This occurs if **send-floodgate-data: true** is set in the Bungee server's Geyser config.  That setting enables Floodgate on the proxy to forward Bedrock data to the Spigot servers.  

With send-floodgate-date:false, WarpSystem and Geyser/Floodgate play together fine...

**To Reproduce**
1. Start with a working bungee network with WarpSystem installed on the proxy and spigot servers.   (Specifically, I'm using latest Waterfall and Paper 1.17.1)
2. Install Geyser and Floodgate on the Bungee proxy
3. Enable "send-floodgate-data: true" on the proxy's floodgate plugin configuration
4. Install Floodgate on each Spigot server
5. Start the bungee proxy and spigot servers
6. Teleport using a cross-server portal or player warp.  It should work fine for a few minutes
7. Wait 5-10 minutes
8. Attempt the same cross-server portal or player warp.  Warp system errors with "The target server is not online".

**Expected behavior**
For WarpSystem and Geyser/Floodgate to coexist on the same bungee network when the proxy is configured to forward Bedrock data to the spigot servers

**Additional context**
Using the following versions of jars on the bungee proxy and spigot servers:

Proxy:
- waterfall-1.17-449.jar
- Bungee_clear.jar
- BungeeSafeguard.main.jar
- BungeeTabListPlus-3.4.4.jar
- floodgate-bungee.jar
- Geyser-BungeeCord.jar
- LuckPerms-Bungee-5.3.48.jar
- protocolize-plugin.jar
- ServerUtils-2.5.6.jar
- ViaBackwards-4.0.1.jar
- ViaVersion-4.0.1.jar
- WarpSystem_v5.0.5.jar

Spigot Servers:
- paper-1.17.1-277.jar
- EssentialsX-2.19.0.jar
- floodgate-spigot.jar
- LuckPerms-Bukkit-5.3.48.jar
- Multiverse-Core-4.3.0.jar
- NashornPlus-1.1.0.jar
- ProtocolLib-4.7.0-SNAPSHOT.jar
- ServerUtils-2.5.6.jar
- Vault.jar
- WarpSystem_v5.0.5.jar

Attached the proxy log file, which showed some unusual packet activity:
[17:57:15] [Geyser player thread-2-1/INFO] [Geyser-BungeeCord]: Team packet  BTLP6da03e79 74 CREATE [~BTLP6da03e79 74, ?]
[17:57:15] [Geyser player thread-2-1/INFO] [Geyser-BungeeCord]: Team packet  BTLP6da03e79 75 CREATE [~BTLP6da03e79 75, ?]
[17:57:15] [Geyser player thread-2-1/INFO] [Geyser-BungeeCord]: Team packet  BTLP6da03e79 76 CREATE [~BTLP6da03e79 76, ?]
[17:57:15] [Geyser player thread-2-1/INFO] [Geyser-BungeeCord]: Team packet  BTLP6da03e79 77 CREATE [~BTLP6da03e79 77, ?]
[17:57:15] [Geyser player thread-2-1/INFO] [Geyser-BungeeCord]: Team packet  BTLP6da03e79 78 CREATE [~BTLP6da03e79 78, ?]
[17:57:15] [Geyser player thread-2-1/INFO] [Geyser-BungeeCord]: Team packet  BTLP6da03e79 79 CREATE [~BTLP6da03e79 79, ?]

**Discord contact**: CougC4t#704
[2021-09-24-7.log](https://github.com/CodingAir/WarpSystem-IssueTracker/files/7228859/2021-09-24-7.log)
0

**Comment by cades66** [comment]
I have this issue as well - it seems to be associated with Floodgate's "send-floodgate-data" setting toggled to true. Toggling it to false allows servers to connect, however this kinda ruins the point of Floodgate.
![image](https://user-images.githubusercontent.com/57970060/135904921-a4b59942-b033-4aad-91c4-cc4307fece22.png)

**Comment by cades66** [comment]
It seems to be working now - I have reason to believe that it was solely a weird ass bug with Geyser + Floodgate, as WarpSystem Premium Hotfix 3 plus Geyser's latest build (https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/900/) and Floodgate's latest build (https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/38/) seems to both work.

**Comment by erikzimmermann** [comment]
I've added a proxy configuration flag to ignore ping issues. You can find that on your proxy under WarpSystem/Config.yml -> IgnorePingErrors (Hotfix#4 can be downloaded from my Discord server)

**Comment by mattc4t** [comment]
Thank you for your support and information on the hotfix.
Regards...
