### ISSUE TITLE
[WarpSystem] Portals incorrectly say the target server is not online.

### ISSUE THREAD

**Issue by EtherealMC-Bit** [erikzimmermann/WarpSystem-IssueTracker#675]
**Describe the bug**
My lobby server has multiple portals leading to other servers. Sometimes when a player tries to use one of these portals they will get a message saying 'the target server is not online', even when there are currently players connected to the destination server. But if another player joins the lobby server WarpSystem seems to realize that the destination server is actually online and they both can join. At some point after this the problem will reappear and another player will not be able to use the portals.

**To Reproduce**
I haven't been able to reproduce it. I have never personally experienced the issue, whenever I join the lobby portals work fine. That might be because I'm an operator. I can give a general setup of the network though:
Bungee - Waterfall 1.18 version 466
Lobby server - Paper 1.16.5 #792
Destination server 1 - Paper 1.16.5 #791
Destination server 2 - Paper 1.16.5 #791

All servers are running WarpSystem 5.0.7 Premium

**Expected behavior**
When a player goes into a portal that has a destination server that's online, they should connect to that destination server.

Discord contact: Bit#3895

**Comment by erikzimmermann** [comment]
Little bit old but check this post if you are using Geyser and Floodgate: https://github.com/CodingAir/WarpSystem-IssueTracker/issues/659#issuecomment-947471323
