### ISSUE TITLE
[WarpSystem] Animation does not turn off.

### ISSUE THREAD

**Issue by mc-eia** [erikzimmermann/WarpSystem-IssueTracker#676]
**Describe the bug**
 Options that worked in previous versions do not work.
-> Animation_After_Teleport:
      Enabled: false

**To Reproduce**
bukkit : purpur 1.18.1 #1462
plugins : WarpSystem Premium 5.0.7 only
1. server start and config change
Animation_After_Teleport:
      Enabled: true -> false
2. server restart
3. run command '/spawn'
4. The animation still works.

**Expected behavior**
-

**Screenshots**
-

**Additional context**
-

**Discord contact**: Bluing#6854

**Comment by erikzimmermann** [comment]
You might have this manually enabled in your teleport feature (portal, sign, whatsoever)
