### ISSUE TITLE
[Error while running this#saveToString()] The plugin doesen't work

### ISSUE THREAD

**Issue by craazytroll** [erikzimmermann/WarpSystem-IssueTracker#677]
The plugin doesen't work. I start the server and there isn't any warp. When I check in the WarpSystem folder many files has this in "Error while running this#saveToString()".
I tried to copy paste from a backup the warp, but every time I restart the server I have the same problem.

I play on a Spingot server in Minecraft 1.18.1 version with the WarpSystem v 5.0.7

**Discord contact**: craazytroll#0019

**Comment by bschlief** [comment]
I'm also seeing this issue.
