### ISSUE TITLE
Add config option to turn off teleport particles when vanished

### ISSUE THREAD

**Issue by OfficialTheosis** [erikzimmermann/WarpSystem-IssueTracker#678]
**Is your feature request related to a problem? Please describe.**
Sort of. When vanished, particles still appear when teleporting, and players may be able to see these particles and deduce that a vanished player is online.

**Describe the solution you'd like**
There should be a configuration option that, when `true`, makes it so that when a player teleports, a check is done to see whether or not they are vanished from the perspective of other (nearby (?)) players, and if they are, those players will not see the teleport particles. Or if it's easier, just don't spawn particles at all if the teleporting player is vanished from the perspective of _any_ player.

This check could be done by hooking into popular vanish plugins such as [PremiumVanish](https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/) and [Vanish No Packet](https://dev.bukkit.org/projects/vanish), or if none are installed, simply using [Player#canSee](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#canSee(org.bukkit.entity.Player)).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Discord contact**: <name>#<id>
Theosis#0001

**Comment by erikzimmermann** [comment]
Vanished players only see their own particles
