### ISSUE TITLE
WarpSystem premium 5.0.7 Error with spamming console and all configs broken.

### ISSUE THREAD

**Issue by Michael-A-Sloan** [erikzimmermann/WarpSystem-IssueTracker#679]
**Describe the bug**
The plugin is nonstop with erroring the console out. It is probably because of an update paper did for build 120.

you also can't update any of the config for some reason as well. I was trying to make the guy popup when the players do /warp but it keeps reseting it.

all configs also show **Error while running this#saveToString()**

**To Reproduce**
1: start server and it starts throwing errors in console.

**Expected behavior**
To work properly and stop spamming.

**Pastbin of console error**
https://pastebin.com/C2J07CGc

there is many more lines but it seems to repeat often.

**Discord contact**: Pup Shadow#0747

**Comment by erikzimmermann** [comment]
Already fixed with #677
