### ISSUE TITLE
"/warpsystem info" shows messed up info

### ISSUE THREAD

**Issue by Andre601** [erikzimmermann/WarpSystem-IssueTracker#68]
Not much to say.
Just run `/warpsystem info` and you get this messed up message:

![image](https://user-images.githubusercontent.com/11576465/58115186-d14bf500-7bf9-11e9-9d35-3a6dd0caf0e9.png)

**Comment by erikzimmermann** [comment]
Oh, that's not nice to look at...
I will improve this!

Thank you for your report.
