### ISSUE TITLE
unused command alias for playerwarp

### ISSUE THREAD

**Issue by FakEEE14** [erikzimmermann/WarpSystem-IssueTracker#683]
hi
because of this 2 options in the playerwarpconfig.yml

    PlayerWarps_Command_Aliases:
    - pwarps
    PlayerWarp_Command_Aliases:
    - pwarp

and this 2 are strongly ignored in commands.yml

    PlayerWarps:
      Name: playerwarps
      Aliases:
      - pwarps
    PlayerWarp:
      Name: playerwarp
      Aliases:
      - pwarp

**Comment by erikzimmermann** [comment]
This is intended. Please use the configuration file.
