### ISSUE TITLE
Tabcompletion for Shortcuts

### ISSUE THREAD

**Issue by VastayanWings** [erikzimmermann/WarpSystem-IssueTracker#687]
**Is your feature request related to a problem? Please describe.**
Not related to any Problems, just a straight suggestion to enhance a feature.

**Describe the solution you'd like**
Creating a shortcut should have an option to add those to automated tab-completion to make it easier for players to use/remember them

**Describe alternatives you've considered**
no alternatives considered (yet)

**Additional context**
no additional context

**Discord contact**: ๖ۣۜζ͜͡𝓥𝓪𝓼𝓽𝓪𝔂𝓪𝓷 𝓦𝓲𝓷𝓰𝓼#1689

**Comment by erikzimmermann** [comment]
Those shortcuts are already registered including tab completion. You only have to restart your server after creating a shortcut.
