### ISSUE TITLE
WarpSystem - Teleport bug

### ISSUE THREAD

**Issue by karlheidar** [erikzimmermann/WarpSystem-IssueTracker#689]
**Describe the bug**
User types /warp home. 
Then user can sprint while the teleport is pending, an when the user stops, the teleport will commence in 3 sec.

**To Reproduce**
1. Create /warp test
2. type /warp test, and start running.
3. Stop running and teleport will commence in 3 seconds.

**Expected behavior**
The behaviour is not normal, and the teleport should be canceled immediately after the user moves.
This can be abused in pvp, because if the teleport is pending, it will bypass the combat timer

**Discord contact**: Mc_VaDeR:0042

**Comment by erikzimmermann** [comment]
Edit: Option to disallow movements before teleport
