### ISSUE TITLE
WarpSystem *- /back command bug

### ISSUE THREAD

**Issue by karlheidar** [erikzimmermann/WarpSystem-IssueTracker#690]
**Describe the bug**
THIS IS FOR SERVER OPERATORS!
When OP uses /warp x, the warp completes successfully.
Howerver when using the /back command, it will return you to the last place you teleported "/tp" not /warped.

**To Reproduce**
1. /tp somewhere
2. place a block, then run 10 blocks.
3. /warp somewhere
4. /back <- this will return you to the place you /tp, not where you used the /warp command.

**Expected behavior**
The /back command only returns you to the last place you initiated the /tp command, not the /warp command.

**Screenshots**

**Additional context**

**Discord contact**: Mc_VaDeR#0042

**Comment by erikzimmermann** [comment]
Works fine more me...
Do you maybe use other tp plugins than mine?

**Comment by derMiepz** [comment]
I had the same issue and CMI installed. Make sure that for whatever plugin you're using, /back is not an alias. In my case /back was an alias for /cmi back and that Alias.yml file wasn't edited / synced on all of my servers.
