### ISSUE TITLE
v5.1.0 hangs on startup | Big config files

### ISSUE THREAD

**Issue by PappoYT** [erikzimmermann/WarpSystem-IssueTracker#695]
**Describe the bug**
After upgrading 5.1.0 server startup hangs when [WarpSystem] Enabling WarpSystem v5.1.0
Startup phase doesn't complete. Server doesn't work.

**To Reproduce**
1. Upgrade to warp 5.1.0
2. start the server

**Expected behavior**
no hangs

**Screenshots**
n/a

**Additional context**
https://mclo.gs/pYPtKU8

**Discord contact**: Pappo#4292

**Comment by erikzimmermann** [comment]
What's NexEngine?

**Comment by PappoYT** [comment]
> What's NexEngine?

it is part of
https://www.spigotmc.org/resources/excellentcrates-advanced-custom-crates-1-16-1-18.48732/

**Comment by erikzimmermann** [comment]
Oh sorry, I stopped scrolling until I saw the first error :D
Please check the config files of WarpSystem. Delete them if they appear to be very large and filled with comments.

**Comment by PappoYT** [comment]
WTH I just saw that my config.yml now is 130Mb!
![config](https://user-images.githubusercontent.com/74958346/157272530-bae7aeea-0382-427a-8a4d-de651bf03c00.PNG)
before update it was 7kb!

**Comment by PappoYT** [comment]
It is full of comments!
![config2](https://user-images.githubusercontent.com/74958346/157272948-43673118-9742-49ef-a7fe-c9656e40681d.PNG)

**Comment by erikzimmermann** [comment]
Yeah, just delete it... It should be fine then

**Comment by PappoYT** [comment]
Ok, I replace all configs file with the backup of this morning (before updating to 5.1.0) and now server starts correctly.
Same problem with TradeSystem config files: they were bigger so I delete them and replaced with backup.
TY for support.
