### ISSUE TITLE
[tpaccept] being able to do tpaccept without having to enter username

### ISSUE THREAD

**Issue by rm20killer** [erikzimmermann/WarpSystem-IssueTracker#697]
**Is your feature request related to a problem? Please describe.**
Narrator does not read out the username of the person who sent the request so people who have difficulty reading chat have a hard time accepting tpa request. 

**Describe the solution you'd like**
Able to type `/tpaccept` and it accepts the most recent tpa request.
Having the message formating so narrator is able to read out the username would also be nice. 

**Discord contact**: RM20#2000

**Comment by Leahcimkrob** [comment]
That would be absolutely great and easier for bedrock players
