### ISSUE TITLE
GriefDefender: protected places activated in the config, allows you to create mywarps in claims

### ISSUE THREAD

**Issue by AlfreDGR** [erikzimmermann/WarpSystem-IssueTracker#700]
**Describe the bug**
Mywarps having the option of not creating in protected places activated in the config, allows you to create mywarps in claims of the griefdefender plugin

**To Reproduce**
3. See error

**Expected behavior**

I would like it if mywarps could not be done within protected claims

**Screenshots**
Griefdefender Claim
![image](https://user-images.githubusercontent.com/62883576/164650745-a397345d-9ad9-444b-9b8d-80331aff62a3.png)

WorldGuard region
![image](https://user-images.githubusercontent.com/62883576/164650947-a2206259-8265-46cf-9ac7-e971570a58a3.png)

**Additional context**

**Discord contact**: Alfre_DGR#6573

**Comment by erikzimmermann** [comment]
Cannot be tested. I don't have GriefDefender.
