### ISSUE TITLE
Players without tp delay bypass are kicked

### ISSUE THREAD

**Issue by BeekrBonkr** [erikzimmermann/WarpSystem-IssueTracker#702]
Players without the permission node `warpsystem.bypass.teleport.delay` are kicked with this message

Pupur-1631 (MC: 1.18.2)

Warpsystem 5.1.0

![image](https://user-images.githubusercontent.com/86544010/172968299-f73dd7d1-520e-42ff-a3cf-50c410001389.png)

**Comment by erikzimmermann** [comment]
Outdated

EDIT: Please bump if this error is still present.
