### ISSUE TITLE
/rtp go und /pwarp geht nicht

### ISSUE THREAD

**Issue by Leahcimkrob** [erikzimmermann/WarpSystem-IssueTracker#704]
Hallo, wir bekomme unter MC 1.19 die folgende Meldung, wenn wir /rtp go nutzen möchten. xTronix hat die Premium erworben. Im Chat kommt "An internal Error"
[message.txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/8903467/message.txt)

**Comment by DeEthria** [comment]
pwarp geht auch nicht 

https://gyazo.com/48c56d1f653b600f4b0900c060e27f45 der Meldeung
