### ISSUE TITLE
BungeeCord: Could not ping server (v5.1.2)

### ISSUE THREAD

**Issue by fof1092** [erikzimmermann/WarpSystem-IssueTracker#706]
**Describe the bug**
Nach dem Update auf Paper 1.19, Waterfall 1.19 und WarpSystem v5.1.2 (Premium Version) funktioniert das Teleportieren zwischen unseren Servern nicht mehr richtig.  (z.b. /gwarp, /tp etc.) 

Bsp: (s.u.)
- Server-1 Kann direkt nach dem Start keine Globalen Warps nutzen.
- Server-2 Kann sie nutzen.
- Server-3 Kann sie nach einiger Zeit nicht mehr nutzen.
- Server-x ...

Auf allen Servern ist WarpSystem v5.1.2. Es gibt keine Fehler beim starten. Testweise hatten wir auch alle WarpSystem Ordner zurückgesetzt.

Im BungeeCord/Waterfall-Log ist mir folgende Nachricht aufgefallen, auf den Paper-Servern gibt es keine Fehler im Log:
```
[23:51:54 WARN] [WarpSystem]: Could not ping server 'CityBuild' due to an error. This results in an inaccessible server. You will not be able to teleport to this server.
[23:51:54 ERROR]: net.md_5.bungee.util.QuietException: Unexpected packet received during ping process! 17787b227472616e736c617465223a22
```

**To Reproduce**
Wie der Fehler reproduziert werden kann, kann ich leider nicht sagen, da es nicht immer zu dem Problem kommt.
Es hilft vermutlich mehrere Server zu nutzen.

Wir verwenden folgende Versionen:
- Paper: This server is running Paper version git-Paper-32 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 4c9317c)
- Waterfall: This server is running Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497 by md_5
- WarpSystem: v5.1.2 [Premium]

**Expected behavior**
Es gibt das Problem nicht.

**Screenshots**
Server-3:
![grafik](https://user-images.githubusercontent.com/12978266/175423699-71d5efb7-1f27-4fff-91f0-3ff94990dc07.png)

Server-1:
![grafik](https://user-images.githubusercontent.com/12978266/175423644-c2c6a51e-e079-4e70-a7ed-e1597c684971.png)

**Additional context**
Auf Basis der Fehlermeldung kann ich nicht sagen, es sich um einen Plugin Fehler handelt oder nicht.

**Discord contact**: F_o_F_1092#9467

**Comment by erikzimmermann** [comment]
Da kann ich leider nichts machen. Falls du Geyser oder Floodgate nutzt, dann setze die Einstellung in der WarpSystem config auf dem Proxy für ignorierende Pings mal auf true. Ansonsten kannst du das temporär auch mal nutzen.

Möglicherweise musst du aber auch nur deinen Proxy aktualisieren
