### ISSUE TITLE
WARP GUI as Inventory Item

### ISSUE THREAD

**Issue by ComputersWithTimo** [erikzimmermann/WarpSystem-IssueTracker#707]
I'm currently using the free Version of WarpSystem and have Warp Signs and a WarpGUI setup.
I'm open to buying the premium version if this feature is/would be included

**Describe the solution you'd like**
I havent found a feature in WarpSystem that allows me to give players who join an Item to open WarpGUI or even better set their Hotbar to such Warps directly

**Describe alternatives you've considered**
ServerSelectorX, PremiumHub 5 (Seems Pretty much dead)

**Additional context**
ServerSelectorX
![2022-07-03_15 06 42](https://user-images.githubusercontent.com/20445379/177041231-506e4475-05e1-4614-88d9-0f2a27b35bf4.png)
![2022-07-03_15 06 46](https://user-images.githubusercontent.com/20445379/177041236-c3619b2a-a170-43c3-87bb-5df5b52ebff2.png)

PremiumHub 5
![2022-07-03_15 08 13](https://user-images.githubusercontent.com/20445379/177041303-8bf59b44-67af-42d3-b783-a49b9af1b3be.png)
![2022-07-03_15 08 18](https://user-images.githubusercontent.com/20445379/177041306-41ef140e-a43d-474d-9258-1768007c15f2.png)

**Discord contact**: 
Timo#2850

**Comment by erikzimmermann** [comment]
Since this seems like a feature for a lobby, it doesn't fit the scope of WarpSystem.
Please use another plugin.
