### ISSUE TITLE
Color codes for warp names don't work anymore on update 5.1.2

### ISSUE THREAD

**Issue by IAmEchino** [erikzimmermann/WarpSystem-IssueTracker#715]
**NOTE: I have intentionally recreated my previous report, #712, in order to properly format it** 

**Describe the bug**
Color codes do not affect the color of warp names in warp messages sent by the plugin.

**To Reproduce**
1. Create Warp with a color code in its name.
2. Warp to that location.
3. The warp message in the chat will not be modified by the color code, and will instead stay as the default cyan/light blue color.

**Expected behavior**
1. Create Warp with a color code in its name.
2. Warp to that location.
3. Color codes will modify the name of the warps in the warp message and will change their color.

**Screenshots**

![image](https://user-images.githubusercontent.com/64720141/185703678-58030d80-6323-40e7-ae63-457e875ad9b8.png)

**Additional context**

This is _not_ a feature request. This worked in the last update, but was broken in the 1.19 update.

**Discord contact**: Echino#8701

**Comment by erikzimmermann** [comment]
Not a bug: https://github.com/erikzimmermann/WarpSystem-IssueTracker/issues/524
