### ISSUE TITLE
RTP between servers not loading world properly

### ISSUE THREAD

**Issue by Parthodys** [erikzimmermann/WarpSystem-IssueTracker#716]
**Describe the bug**
World fails to load properly if using random teleport to a world on another server.
Leads to hanging in air and not being able to move / getting stuck on "Loading terrain..." screen / falling in the air endlessly.
Issue has existed since at least October 2021 on multiple game versions (1.17.1 & 1.19, Paper/Waterfall).

**To Reproduce**
1. In 1st server: /rtp go [lobby; lobby@world1]
2. Sends you to world on 2nd server
3. Get stuck in the air with world not loading or stuck on "Loading terrain.." screen.
Optional 4. Reconnect and world will load

**Expected behavior**
World loading successfully, as with rtp to a world on the same server.

**Screenshots**
![2022-09-05_14 47 19](https://user-images.githubusercontent.com/1515422/188445417-3cf36b3b-da92-4483-aaf0-e1d206b2b761.png)
![2022-09-05_14 48 24](https://user-images.githubusercontent.com/1515422/188445442-29f2a0e4-f6f0-4a04-9e2a-177c73d94c11.png)
![2022-09-05_14 46 45](https://user-images.githubusercontent.com/1515422/188445453-431beee9-4069-4c81-8b6c-7c2ed90a7925.png)

**Discord contact**: Graddod#9153

**Comment by xcoolerboy** [comment]
got same issue when dev will fix this??

**Comment by Parthodys** [comment]
Any updates on this? It would be nice if this worked properly, teleport could be smooth. 
Currently using a workaround by teleporting players into a portal that then triggers random teleport, its a bit wonky at times as some players load slower than others.
