### ISSUE TITLE
[RTP] Not finding any good locations

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-IssueTracker#718]
**Describe the bug**
Recently, users report the random teleporter to perform badly.
More investigation is needed.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/23747243/189323034-8806aa7a-4b6f-462d-851a-cd88bd217795.png)

**Additional context**
N/A

**Comment by DaycareJr** [comment]
I have this same issue... Its basicly stopping my server from launching please fix soon...
