### ISSUE TITLE
[General] SetupAssistant and Options error

### ISSUE THREAD

**Issue by dominoxp** [erikzimmermann/WarpSystem-IssueTracker#725]
**Describe the bug**
Server error while executing commands

**To Reproduce**
1. Enter Command /warpsystem options 
2. Or Enter Command /warpsystem setupassistant
3. See error (An internal error occurred while attempting to perform this command)

**Expected behavior**
No error message

**Screenshots**

**Additional context**
Permium Plugin Version 5.1.3 with bungeecord and spigot
[server.log](https://github.com/erikzimmermann/WarpSystem-IssueTracker/files/10006277/server.log)

**Discord contact**: dominoxp#9469

**Comment by erikzimmermann** [comment]
This is aleady fixed with #720 and can be downloaded on my [Discord server](https://discord.gg/4eVAhKz) via the dev-builds-free or dev-builds-premium channel.
