### ISSUE TITLE
WS 5.1.3 big number coordinate issues with SimpleWarps

### ISSUE THREAD

**Issue by terbin** [erikzimmermann/WarpSystem-IssueTracker#731]
**Describe the bug**
Running latest WarpSystem 5.1.3 Hotfix 5 on Paper 1.19.3
Any warp that's far out, for example 1 million, 1 million, teleports the player to max coords that look like a max 32 bit integer.
214784 is the maximum coordinate a SimpleWarp will send me to

This is not an issue in WarpSystem 5.1.2

**To Reproduce**
1. Start WarpSystem 5.1.3 Hotfix 5 on a 1.19.3 Paper server
2. Teleport far out, for example /tp 1000000 70 1000000
3. Set a warp
4. warp to this warp

**Expected behavior**
Correct teleport to coordinates far out

**Comment by deskgnome** [comment]
Noticed this happening on my server as well.

**Comment by terbin** [comment]
@erikzimmermann this issue is not fixed in 5.1.4

**Comment by deskgnome** [comment]
I am no longer experiencing this error.  5.1.4 fixed it for me - thanks!

**Comment by terbin** [comment]
It works for things in the 200k block range.
Warps to 1 million, 1 million or further still exhibit this issue.

**Comment by terbin** [comment]
I apologize. I did not restore a backup and was using existing warps. It is indeed fixed in 5.1.4.

**Comment by terbin** [comment]
Hi Erik, is this something I can test in hotfix 1 of 5.1.5?

For now I reverted to 5.1.2
