### ISSUE TITLE
`/setspawn` works incorrectly: re-spawns payers on top of blocks, not at the exact spawn coords

### ISSUE THREAD

**Issue by VladOliinyk** [erikzimmermann/WarpSystem-IssueTracker#735]
**Describe the bug**
`/setspawn` works not as it is expected to.

I have a spawn set inside the building. But after deaths, players who do not have their beds spawn at the top of the building. why?!
if I turn on Use for respawn option locally - all players even with their own spawn points near their bed are spawning on spawn.

How the heck can I set the respawn point at the exact coords I want, but not where the game is thinking to be good to respawn a player??

`/setworldspawn` - does not works, the payer is respawned on top of the highest block.
`/gamerule spawnRadius 0` - do not really help 

**To Reproduce**
1. find a location where there are some blocks above the player (not a clear sky)
2. set spawn via /setspawn
3. make sure that `use for spawn` setting is disabled in `/setspawn edit` (to not override the bed-spawn, right?)
4. clear your bed-respawn point (destroy bed)
5. die (not in real life bruh)
6. the issue: you are respawned on top of the spawnpoint. X and Z are ok, but Y is wrong. 

**Expected behavior**
I gues the respawn point needs to be the exact coords where the `/setspawn` command were issued

**Discord contact**: OilMan#0036

**Comment by erikzimmermann** [comment]
Well, you probably had some other plugin enabled. Like Multiverse or Essentials. I'm gonna close this now
