### ISSUE TITLE
Target server is not displayed - Nova Modding Framework

### ISSUE THREAD

**Issue by Lice2** [erikzimmermann/WarpSystem-IssueTracker#736]
**Describe the bug**
I installed the Nova Modding Framework plugin on the server. And if I make portals create name, it also works so far, I can also set the portal blocks, only if I then want to select the target server, nothing comes up.
Plugin : Nova | Modding Framework | [1.19.3] 0.12.15
Paper Server 1.19.3-392
WarpSystem Premium 5.1.5

portal create Zum-Survival-Server
Portal blocks placed
block dropped
Right click on the ender pearl
Server selection, from there comes the error message in the console.

**Additional context**
(https://pastebin.com/dRKLz9L3)

**Discord contact**: Lice#6521

**Comment by erikzimmermann** [comment]
This is an issue with the Nova Modding Framework
