### ISSUE TITLE
pwarps gui and mcmmo

### ISSUE THREAD

**Issue by audicu707** [erikzimmermann/WarpSystem-IssueTracker#741]
**Describe the bug**
pwarp gui causes mcmmo to give herbalism xp when there are flowers around

**To Reproduce**
there is a video about it
https://www.mediafire.com/file/yhkija60ghey03x/Minecraft__1.19.2_-_%25C3%2587ok_Oyunculu_%25283._Taraf_Sunucu%2529_2023-03-07_21-39-50.mp4/file

Discord: audicu707#7469

**Comment by erikzimmermann** [comment]
What exactly should be changed?

**Comment by audicu707** [comment]
You can add option to disable pwarp gui and pwarps can be only used with commands or you can find the problem that what causes to give mcmmo herbalism xp when there is flowers around teleported place.
