### ISSUE TITLE
cooldown for random teleport not working

### ISSUE THREAD

**Issue by xcoolerboy** [erikzimmermann/WarpSystem-IssueTracker#743]
hello so if you add command on deluxe menu to player do action like
- '[console] randomtp go [survival; survival@world] %player_name%'
- or even this
-  '[player] randomtp go [survival; survival@world] 
- the cooldown wont count and player can do it

**Comment by erikzimmermann** [comment]
The cooldown is now applied to the go command. When running the teleport command via console, the cooldown will be skipped.
