### ISSUE TITLE
1.20 Proxy Support

### ISSUE THREAD

**Issue by Parthodys** [erikzimmermann/WarpSystem-IssueTracker#749]
**Describe the bug**
Plugin has an exception when loading and does not start on 1.20 Waterfall.
https://pastebin.com/SrZZWjXi

**Discord contact**: <name>#<id>
@Graddod

**Comment by joshwenke** [comment]
This is a high priority for us!

**Comment by Parthodys** [comment]
@erikzimmermann Indeed it is, network lacking all the portals and teleports, very problematic.

**Comment by AlexanderMandera** [comment]
I have found a fix for this error: https://github.com/erikzimmermann/CodingAPI/pull/25
I think @erikzimmermann may look at this tomorrow and publish it then.

When you can't wait and want the fix before it is a real version,
you can copy the `de` folder from the attached ZIP into your WarpSystem.jar file using 7zip or a similar tool.

[WarpSystem BungeeCord 1.20 Fix.zip](https://github.com/erikzimmermann/WarpSystem-IssueTracker/files/11693105/WarpSystem.BungeeCord.1.20.Fix.zip)

I can't guarantee that everything else works without errors
but it does not throw the mentioned error on startup with this.

If you aren't able to patch the JAR like this, you need to wait for the updated version.

**Comment by AlexanderMandera** [comment]
Fixed in 5.1.6 Hotfix 1.
