### ISSUE TITLE
Warp System - Global Warps not listing properly in selection GUI

### ISSUE THREAD

**Issue by braceyourself07** [erikzimmermann/WarpSystem-IssueTracker#759]
**Describe the bug**
Whenever I'm in a gui to select a global warp, the item in the gui disappears when I try to select it.

![2023-11-10_20-22-57](https://github.com/erikzimmermann/WarpSystem-IssueTracker/assets/4984394/7f5ac17d-d4c7-438e-82ac-eb687489cee5)

And the icons on the right aren't the usual red and green Cancel/Accept buttons in the pwarp list.
Not sure if it's related, but at the same time, I get this spammed in console:  

`[01:26:47 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.`

**To Reproduce**
1. /shortcut create somename
2. Click on Destinations then Global Warps
3. Try to select a global warp, but the GUI icons disappear and it's not the usual green/red accept/discard buttons on the right.

**Expected behavior**
I should be able to select a global warp from the GUI and save clicking on the green block.

**Discord contact**: mikedmd

**Comment by erikzimmermann** [comment]
What server version do you use? 1.20.2?

**Comment by braceyourself07** [comment]
Yes, 1.20.2.  However, I just tried to set a shortcut again and it worked.   ¯\\_(ツ)_/¯
In retrospect, I have a feeling the proxy version was not the same as the spigot version and that may have resulted in the conflict. But for now, this is no longer an issue.

**Comment by erikzimmermann** [comment]
Alright. I've also no problems on my side 👍🏻
