### ISSUE TITLE
[WarpSystem] PLHİDE-PRO command protector

### ISSUE THREAD

**Issue by xCrueltys** [erikzimmermann/WarpSystem-IssueTracker#763]
Actually, this is not exactly a mistake. Plhide plugin has a command protector feature, this feature ensures the security of the server.
However, when I enter the actions made by clicking on the chat in warpsystem in the command blocker, it does not work.
For example, when we do rtp buy, yes or no comes up and when I click on them, it says the command was not found.
This is because you are using Codinair|chataapi|button|***
I wonder how exactly I can enter the API you used into this plugin?
Plugin owners told me to learn the API from you and enter it

**Server version**: <1.20.1>
**Discord contact**: <xCrueltys>

![image](https://github.com/erikzimmermann/WarpSystem-IssueTracker/assets/153362465/0afc57fb-aa71-4629-a524-528a26d35275)

**Comment by erikzimmermann** [comment]
Since my latest hotfix, there's a `confirm` option: `/rtp buy confirm`. You can use that for your PLHide plugin
