### ISSUE TITLE
PlayerWarps & Portals Can't Name / Rename with latest hotfix

### ISSUE THREAD

**Issue by joshwenke** [erikzimmermann/WarpSystem-IssueTracker#765]
**Describe the bug**
The playerwarps system does not allow you to name or rename warps using the GUI
ALSO the portals create/naming system is broken too. 
![image](https://github.com/erikzimmermann/WarpSystem-IssueTracker/assets/1607041/0d6fae71-2a8a-4320-a3e4-e850dc057637)

**To Reproduce**
1. Open PlayerWarps
2. Click Create

**Expected behavior**
Expect the normal anvil naming screen to come up

**Additional context**
**Plugin version**: 5.1.9_Hotfix-2
**Server version**: git-Paper-381 (MC: 1.20.4)
**Discord contact**: joshwenke

**Comment by KenGrinder** [comment]
Are you also having this same issue when trying to name a portal using /portals create?

Having a similar issue and wanted to verify if it may be related before submitting a new bug.

**Comment by joshwenke** [comment]
@KenGrinder Yes, that is the exact same issue we are having. Looks like it is the same code for both. I have updated my issue to reflect that.

**Comment by RiegerMolgur** [comment]
I have the same Problem.

**Comment by Loving11ish** [comment]
And here too.  It is due to the reworking of GUI opening packets in 1.20.4.  Mojang added the new auto crafter GUI packets into 1.20.4 as part of the experimental 1.21.0 features and it has messed with some packet ID's.  Hopefully there will be a fix from WS devs soon.

**Comment by joshwenke** [comment]
For those following along here that may not be in the Discord, here is what the author said about getting this fixed
<img width="519" alt="image" src="https://github.com/erikzimmermann/WarpSystem-IssueTracker/assets/1607041/22ff8cc1-0b05-4018-872e-fd89e46b3be2">
