### ISSUE TITLE
Dependency ID 'Trevor' for plugin 'warpsystem' is invalid

### ISSUE THREAD

**Issue by EmanYm** [erikzimmermann/WarpSystem-IssueTracker#770]
**Describe the bug**
Premium Warp System 5.1.9 does not start on Velocity 3.3.0 build 360

**To Reproduce**
1. Install Velocity 3.3.0 build 360
2. install (premium) WarpSystem 5.1.9
3. See latest log

**Expected behavior**
Expected to not need Trevor for a single-proxy network.

[latest log](https://mclo.gs/uBPSAvJ)

**Discord contact**: Eiple (@forgottenfreedommc)

**Comment by EmanYm** [comment]
Any progress on this?  I can't create or edit any global/network warps because the proxy version is broken.
I downgraded all the way back to 5.1.7 and I'm still getting this same issue.

Not sure if this is related, but the GUI is wonky, [this is from trying to name a new warp](https://gyazo.com/41e07002c2e2c25507270bbd9177c40f).

EDIT:
I'm going to try downgrading Velocity...

EDIT2:
I rolled Velocity v3.3.0 back through each build from 360 to 355:
Velocity 360 + WarpSystem 5.1.9 to 5.1.5
Velocity 359 +  ^
.....
Velocity 355 + ^
All somehow had the same problem.

**Comment by EmanYm** [comment]
I got around the Trevor dependency requirement by removing the following block from the velocity-plugin.json

>   "dependencies": [
    {
      "id": "Trevor",
      "optional": true
    },
    {
      "id": "RedisBungee",
      "optional": true
    }
  ],

But the GUI is still messed up.  It spams the following in my console when I attempt to do almost anything in the gui
> 19.02 21:19:36 [Server] WARN Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
19.02 21:19:36 [Server] INFO Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
19.02 21:19:36 [Server] INFO If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).

**Comment by EmanYm** [comment]
I compared the WarpSystem's velocity-plugin.json with that of another multi-platform plugin and noticed two things.

- The other plugin's file is all on the same line, it's not nested
- They have no space between "optional": and true

After I restart my machine I'm going to see if collapsing the contents of the WarpSystem velocity-plugin.json will help with the Trevor dependency issue


EDIT:
Collapsing and removing spaces from the .json file did not change the Trevor error.
The only thing that has worked so far is removing that block from the velocity-plugin.json entirely.

**Comment by bitrot-alpha** [comment]
Issue still occurs on Velocity 385 and 5.1.10 download from SpigotMC.org

![image](https://github.com/erikzimmermann/WarpSystem-IssueTracker/assets/55378293/b9f11808-4608-41e3-bea9-ab6706fdfad0)

**Comment by bitrot-alpha** [comment]
May be a regression on Velocity's side, see https://github.com/PaperMC/Velocity/pull/1231 (build 347)

I downgraded to Velocity 3.3.0 build 316 and WarpSystem 5.1.7 since my backends are still 1.19.4 and now WarpSystem works again.

**Comment by bitrot-alpha** [comment]
removing the dependencies block from the json file still works for 5.1.10 and Velocity build 385.
