### ISSUE TITLE
memory leak issue on server

### ISSUE THREAD

**Issue by xcoolerboy** [erikzimmermann/WarpSystem-IssueTracker#775]
hello there codingair there is little bit of memory leak issue just wanted to report it for fix

![image](https://github.com/erikzimmermann/WarpSystem-IssueTracker/assets/51112473/8346cc3b-143d-4daf-9d48-ee46815f556b)
![image](https://github.com/erikzimmermann/WarpSystem-IssueTracker/assets/51112473/87a79d74-15e7-4595-b72c-b3d840b0410b)

**Comment by erikzimmermann** [comment]
Seems like you have a really big config file 🤔 Since I'm using the YamlConstructor, there's nothing I can really do about it...
