### ISSUE TITLE
Wormholes/Stargate

### ISSUE THREAD

**Issue by CodeDoctorDE** [erikzimmermann/WarpSystem-IssueTracker#96]
https://www.spigotmc.org/resources/wormholes-portals-you-can-see-through.43188/ Wenn das geht, respekt!

Wenn nicht ist auch egal!

Aber unbedingt das hier:

https://www.spigotmc.org/resources/stargate-ultimate-teleporting-warping-solution.8956/

Was davon?
- Ziel selber aussuchen
- ggf. Animation

**Comment by CodeDoctorDE** [comment]
Vielleicht mit Schildern oder Gui und nicht mit einem Zahlenschloss. Das man einfach das Ziel aussuchen kann. So wie das WarpGui z.b. nur für jedes Portal anders

**Comment by erikzimmermann** [comment]
Passt nicht zum aktuellen Portal. Das Bearbeiten wäre viel zu komplex.

Wormholes sind zu ressourcenfressend. Es müssten ganze Chunks geladen und versendet werden. Die Wartung davon wäre zu immens.

**Comment by CodeDoctorDE** [comment]
Dann vielleicht ohne Durchgucken. Einfach für Nativeportals ein Schild zum selektieren hinzufügen
